### ISSUE TITLE
Override config with msg

### ISSUE THREAD

**Issue by xoseperez** [586837r/node-red-contrib-alexa-remote2#1]
Hi! 
Great node and it would be awesome if you could override some settings with message properties, in particular, serialOrName, command, value and target.

**Comment by 586837r** [comment]
Thank you!
You can currently set each settings field to use a msg, flow or global property by clicking on the dropdown on the left side of the input field. Is this what you were asking for?

**Comment by 586837r** [comment]
I just noticed that setting the target/Command/Request this way does not work. I will fix that.
#2

**Comment by xoseperez** [comment]
I'm not sure of what you mean, there is no selector on the left side of the input fields on the sequence node, for instance. There are two in the configuration node, but they are not functional.

![node red2](https://user-images.githubusercontent.com/706487/49685173-11ea0300-fadf-11e8-8d03-febda4b7391f.jpg)

![node red](https://user-images.githubusercontent.com/706487/49685174-11ea0300-fadf-11e8-851d-a26eb60bb568.jpg)

**Comment by 586837r** [comment]
Oh that's wierd, it looks different on my end:
![capture2](https://user-images.githubusercontent.com/871782/49685843-abb7ad00-faeb-11e8-9fae-831e591e5186.PNG)
![capture](https://user-images.githubusercontent.com/871782/49685844-abb7ad00-faeb-11e8-9d6d-f2f8f59fc0a6.PNG)
Do you see the dropdown in native nodes like *change*?
What browser are you using and what versions are you running?
It works for me on the most recent Chrome and Firefox and with 
Node-RED version 0.19.4 and Node.js version 8.12.0/10.13.0.
