### ISSUE TITLE
How to Stop streaming e.g. TuneIn or AmazonMusic 

### ISSUE THREAD

**Issue by RedCross0815** [586837r/node-red-contrib-alexa-remote2#10]
Iam playing a while with this node and i have to say thank you for the good work and the time you spend for the project. 
Everything works fine, but i cant find a little thing:
Is there any possibility to STOP streaming TuneIn or AmazonMusic for example? 

Thank´s a lot

BR 
Thomas

**Comment by 586837r** [comment]
Thank you. You can pause music with the alexa remote command node, select the pause command.
