### ISSUE TITLE
How long does the cookie last

### ISSUE THREAD

**Issue by NovaGL** [586837r/node-red-contrib-alexa-remote2#11]
How do I find out how long the cookie lasts so I know when to refresh it.

Is there any way that I can automatically refresh it?

**Comment by Prog72** [comment]
I am also keen to know this as it seems to expire randomly. Sometimes it lasts a few days, other times a few weeks.

**Comment by joshimosh** [comment]
Same for me. I just discovered that my old cookie did not work and I had to get the new (?) cookie.
An automatic refresh would be wonderful.

**Comment by orimate** [comment]
I would be interested.

**Comment by RedCross0815** [comment]
Is there any solution for a automatic refresh?

**Comment by 586837r** [comment]
Automatic refresh is now possible when using the proxy authentication. **2.0.0**

**Comment by NovaGL** [comment]
Will try and let you know.
Thanks!

**Comment by 586837r** [comment]
You are right Language was being ignored. It should work now (v2.2.2), thanks for reporting!
You can store it however you want. 
You will have to use a *Alexa Init* node to initialise the account. On success it will output an object that you can save and later to feed it into the *Alexa Init* node to initialise the account automatically.
I recommend turning Auto Init in the *Alexa Account* off if you initialise it that way. This is now also described in the *Alexa Init* node info.

**Comment by NovaGL** [comment]
Thanks. It keeps loosing the config each time I add a node. Maybe this update will fix it

**Comment by 586837r** [comment]
Hold on, do you mean that the Account settings get lost or do you mean it has to reinitialise?
And that everytime you add a e.g. Alexa Sequence node?

**Comment by NovaGL** [comment]
It asks me to goto the proxy page every time  should have been clearer.

**Comment by 586837r** [comment]
Ok i see.
When you change an Account setting it will reinitialise. But it seems that if you just open the Account for editing but change nothing and then press update it will reinitialise. So instead just press cancel.
If you just select the Account for your e.g. Alexa Sequence node it should not reinitialise...

**Comment by NovaGL** [comment]
But it is. I delete a node add another select the config. Press deploy and I need to goto the proxy again.

**Comment by 586837r** [comment]
While testing i've had it happening a few times too but quite sporadically. Thanks for bringing this up. I'll try to find the cause. In the meantime i suppose you can disable *Auto Init* in the account and use *Alexa Init* to initialise it. Hopefully it won't happen then..

**Comment by NovaGL** [comment]
I'm confused. Now it just says account not intialised. How do I use the cookie I got from the init node?

**Comment by 586837r** [comment]
Like this:
```
[{"id":"323608dd.6ee4c8","type":"inject","z":"ba312d1.b9842d","name":"","topic":"","payload":"alexa","payloadType":"flow","repeat":"","crontab":"","once":false,"onceDelay":0.1,"x":120,"y":80,"wires":[["50b011bc.1d8b1"]]},{"id":"415d7558.7fbcfc","type":"change","z":"ba312d1.b9842d","name":"","rules":[{"t":"set","p":"alexa","pt":"flow","to":"payload","tot":"msg"}],"action":"","property":"","from":"","to":"","reg":false,"x":410,"y":80,"wires":[["afc17e7c.70e288"]]},{"id":"afc17e7c.70e288","type":"debug","z":"ba312d1.b9842d","name":"","active":true,"tosidebar":true,"console":false,"tostatus":false,"complete":"false","x":570,"y":80,"wires":[]},{"id":"50b011bc.1d8b1","type":"alexa-remote-init","z":"ba312d1.b9842d","name":"","account":"","x":260,"y":80,"wires":[["415d7558.7fbcfc"]]}]
```
Press the inject node and initialise it manually once. Following initialisations via this inject should be automatic. Does that work?
