### ISSUE TITLE
Any way to get alexa to make chime/doorbell sound?

### ISSUE THREAD

**Issue by 877dev** [586837r/node-red-contrib-alexa-remote2#110]
Thanks for the great nodes, I have it speaking etc. no problems at all.

But, I would like a node red flow to trigger alexa to make a chime/doorbell sound. 
Possible?

Thanks

**Comment by 586837r** [comment]
Sounds are now added as a Routine node option in 3.10

**Comment by 877dev** [comment]
Awesome thanks, I’ll check it out in the morning 👍

**Comment by 877dev** [comment]
Update: working, thanks very much!
