### ISSUE TITLE
entities.map is not a function

### ISSUE THREAD

**Issue by schlak** [586837r/node-red-contrib-alexa-remote2#112]
When i'm trying to initialise my setup i get the error shown below in the screenshot.
I included my configuration where i starded very simple. Have i miss something?

![image](https://user-images.githubusercontent.com/26164340/76842808-287f1e00-683b-11ea-9669-d4ca48217be7.png)
![image](https://user-images.githubusercontent.com/26164340/76842837-32a11c80-683b-11ea-9cf6-4a7f7175f4fd.png)
![image](https://user-images.githubusercontent.com/26164340/76842328-63348680-683a-11ea-9dfe-00f1e60a00bf.png)

**Comment by 586837r** [comment]
This is just a warning that it could not load the Smarthome devices. Potentially you don't have any smarthome devices? In the next patch the warning message will be clearer.
