### ISSUE TITLE
Improvement request: support whisper mode

### ISSUE THREAD

**Issue by bwims** [586837r/node-red-contrib-alexa-remote2#117]
Is it possible to implement the new whisper mode?  It would be great to be able to whisper information at night time in response to e.g. a remote button.

**Comment by 586837r** [comment]
Whispering is already possible via the SSML option with a text like this:
```xml
<speak>
    <amazon:effect name="whispered">Good Morning.</amazon:effect>
</speak>
```
Have a look at the SSML examples for other effects!

**Comment by bwims** [comment]
Thank you!  Sorry to have been a noob!
