### ISSUE TITLE
Improvement request - play music via stream URL

### ISSUE THREAD

**Issue by bwims** [586837r/node-red-contrib-alexa-remote2#119]
Me again.... I wonder if this is possible, or something that could be added?

According to https://developer.amazon.com/blogs/post/Tx1DSINBM8LUNHY/new-alexa-skills-kit-ask-feature-audio-streaming-in-alexa-skills,

It's possible to get Alexa to stream from a URL - intended for skills, but as your routine exposes a lot of the internal of skills, I wondered whether it a possibility to get Node Red to play a URL stream.

Wouldn't that be nifty?

**Comment by 586837r** [comment]
That would be great, but i don't see a way to access this feature. 
Whatever is accessible in the Alexa web interface or app could be added but this is not. 
Note that SSML should already be able to do this (#17) but it is not enabled by Amazon for the way we use it.

**Comment by bwims** [comment]
Shame!

Thanks anyway!

**Comment by bwims** [comment]
FYI  This link seems to explain the limitations  on audio.  It mentions
that you can stream as long as the audio meets the limitations, but the
limitations are certainly limited....

https://developer.amazon.com/en-US/docs/alexa/custom-skills/speech-synthesis-markup-language-ssml-reference.html#audio-specs
