### ISSUE TITLE
"Amazon-Login-Error: Wichtige Mitteilung!: Zum besseren Schutz Ihres Kontos geben Sie bitte nochmals Ihr Passwort ein, und geben Sie dann die Zeichen ein, die in der Abbildung unten gezeigt werden."

### ISSUE THREAD

**Issue by MiguelESP89** [586837r/node-red-contrib-alexa-remote2#12]
Hey i updated node js to 10.x
now i wanted to login with my account details User and Passwort. 
The Problem is that i get a failure. 
 "Amazon Login error: Important Notice!: To better protect your account, please re-enter your password, and then enter the characters shown in the illustration below. "

The Problem is that i didn't see any characters :D 

Can anyone help me?

Regards 
Miguel

**Comment by 586837r** [comment]
> ### Logging in with Email and Password
>  * will not work if Captcha or 2 Factor Authentication is needed

Looks like you would need to pass a captcha. This is not supported by these nodes. You will need to manually enter your Cookie.
