### ISSUE TITLE
Questions and answers from Alexa

### ISSUE THREAD

**Issue by federico2015** [586837r/node-red-contrib-alexa-remote2#120]
Is it possibile to make a question from Alexa devices and receive the answer?

**Comment by 586837r** [comment]
Yes, you get a **Device Activity** event to the **Alexa Event** node when talking to an echo.
Your Echo will try to answer itself though so creating a routine that triggers a  virtual device might make more sense.

You can create virtual devices with `node-red-contrib-alexa-smart-home` or `node-red-contrib-amazon-echo`.

**Comment by peteakalad** [comment]
Tried to use Device activity for this, but no luck.

I'm not sure its possible?   So triggered from node-red (NOT saying a keyword) Alexa would ask a question and then await an answer?

e.g. node red would poll the door lock every 5mins, and if it finds it unlocked it was trigger a 'Routine Speak' node for alexa to say "I noticed the door is open, do you want me to unlock it?" with alexa automatically waiting a Yes/No response and not having to say 'Alexa' to trigger it.  Is this later prompt/question without having to say 'Alexa' possible?

I note its possible with a home assistant plugin but was hoping I could do it with node-red only
https://github.com/keatontaylor/alexa-actions

**Comment by hazymat** [comment]
I have this question too, as detailed by @peteakalad

**Comment by Varguit** [comment]
Hi @peterchs  and @hazymat .
Did you managed to find a way to make this work?
I was able to make an Alexa skill to ask for example: "It's dark, do you want to switch the lights on?" and then waits for a Yes/No
You can call this skill directly from **Alexa routine** node and then receive the answer through **On device activity** node.
What I'm struggling at, is how to make it more dynamic. I mean, how to make a skill that gets data (question) from NodeRed and post the response back indicating which was the question.

**Comment by hazymat** [comment]
Hi @Varguit Can you detail exactly how you did this "it's dark, do you want to switch the lights on" routine in Node-RED? I know how to get it to speak, but can you explain how to prompt? The more detail you can provide, the better! I may be able to help with the second part to your question, after that!

**Comment by Varguit** [comment]
Hi @hazymat. Of course I can explain you what I've achieved so far.

1- If you want alexa to prompt, you need to create a Custom skill. 
Assuming you already know how to create one (I can guide you through the process if not..), you just need to create an intent called, for example, OfficeLight with an utterance (ex. turn office light)
On the code part you have to add this handlers:


```
function setQuestion(handlerInput, questionAsked) {
    const sessionAttributes = handlerInput.attributesManager.getSessionAttributes();
    sessionAttributes.questionAsked = questionAsked;
    handlerInput.attributesManager.setSessionAttributes(sessionAttributes);
}

const OfficeLightIntentHandler = {
    canHandle(handlerInput) {
        return Alexa.getRequestType(handlerInput.requestEnvelope) === 'IntentRequest'
            && Alexa.getIntentName(handlerInput.requestEnvelope) === 'OfficeLight';
    },
    handle(handlerInput) {
        const speakOutput = 'Do you want me to turn the office light on?';
        setQuestion(handlerInput, 'OfficeLight');

        return handlerInput.responseBuilder
            .speak(speakOutput)
            .reprompt(speakOutput) // Session still open
            .getResponse();
    }
};

const YesIntentHandler = {
    canHandle(handlerInput) {
        return Alexa.getRequestType(handlerInput.requestEnvelope) === 'IntentRequest'
            && Alexa.getIntentName(handlerInput.requestEnvelope) === 'AMAZON.YesIntent'
            && handlerInput.attributesManager.getSessionAttributes().questionAsked;
    },
    handle(handlerInput) {
        const sessionAttributes = handlerInput.attributesManager.getSessionAttributes();
        let speakOutput = 'no questionAsked';


        if (sessionAttributes.questionAsked === 'OfficeLight') {
            speakOutput = 'All right, I turn the office light on';
        }

        return handlerInput.responseBuilder
            .speak(speakOutput)
            //.reprompt(speakOutput) // This ends the session
            .getResponse();
    }
}; 

```
You can add more intents , this is just an example.

2. On the Node red part
Assuming you already have alexa-remote2 working (I'm using remote2-appelstrudel), you have to add alexa routine node , use Text command and insert the text to invoke your skill with the intent : 
`ask <skill invocation phrase> to turn <intent name>` (ex: "ask node red skill to turn office light")
and then with the node OnDeviceActivity you can catch if the users says Yes and do whatever you want.

![image](https://user-images.githubusercontent.com/34375733/162951264-f63f7b01-60da-4138-82cd-3821d8eb5159.png)

I hope this helps , ask me if you need more detail
