### ISSUE TITLE
EISDIR, Illegal operation on a directory, Read

### ISSUE THREAD

**Issue by bdydrp** [586837r/node-red-contrib-alexa-remote2#122]
I get this error when trying to authenticate an Australian account.
I have full read/write permissions to my file path i put.
NR running on docker (unraid)

Any assistance appreciated
Cheers

**Comment by 586837r** [comment]
It needs a path to a file like `~/alexa-cookie.json` not to a directory!

**Comment by bdydrp** [comment]
I have tried a path to a file like you mentioned. 
Used `~/alexa.cookie.json` , `~/cookie.txt`
Both instances, i even created the file in the directory.
This is the error:
ENOENT: no such file or directory, open '~/cookie.txt'

**Comment by bdydrp** [comment]
> It needs a path to a file like `~/alexa-cookie.json` not to a directory!

Sorry to bring it uyp again after its closed but, 
I have tried a path to a file like you mentioned.
Used `~/alexa.cookie.json` , `~/cookie.txt`
Both instances, i even created the file in the directory.
This is the error:
ENOENT: no such file or directory, open '~/cookie.txt'
