### ISSUE TITLE
Working in Canada?

### ISSUE THREAD

**Issue by sktaylortrash** [586837r/node-red-contrib-alexa-remote2#125]
Does anyone have this working for Canada?  I know our Alexa page is alexa.amazon.ca rather than .com and presumably, the language is EN-CA.  
But setting that doesn't seem to work

Any thoughts?

**Comment by CaptainSweatpants** [comment]
It works. 
-Service host: pitangui.amazon.com
-page: amazon.ca
-language: en_US

**Comment by sktaylortrash** [comment]
My apologies I forgot I asked this.  I rebuilt my node-red from scratch and then it worked
