### ISSUE TITLE
buildUiJson is not defined

### ISSUE THREAD

**Issue by emme73** [586837r/node-red-contrib-alexa-remote2#126]
Got an issue using the initialize node to refresh cached states
by my understanding the sinple flow 
![image](https://user-images.githubusercontent.com/26736389/80461926-4b224d80-8936-11ea-9ecf-ba338fb41a07.png)
is suppoed to refresh the states and update the list of available smarthome devices and entities
the inject is configured to issue a payload = true just to trigger the node.
Unifortunately, triggering it result into an error:
![image](https://user-images.githubusercontent.com/26736389/80462044-7442de00-8936-11ea-9a4a-e09a4409c70d.png)
the node generates this error
`Cannot read property 'initDevicesExt' of undefined`
and the status node report 
`buildUiJson is not defined`

account has to be reinitialize back (I use cookie file on filesystem) and it works back again

**Comment by 586837r** [comment]
This bug is now fixed in 3.10.1 thanks for the report!
