### ISSUE TITLE
Less logging or more control over it

### ISSUE THREAD

**Issue by giddyhup** [586837r/node-red-contrib-alexa-remote2#127]
It's still a great solution and I understand that logging is essential for debugging but it seems there are regularly ocuring messages about updates (added, started, applied, popped, etc.) that flood my syslog. Is there a way to disable it?

(I, for one, know that I can set up a rsyslog filter but perhaps this is something that can also be set in the source.)

**Comment by 586837r** [comment]
You should only get flooded with logging if you set the logging level in Node-RED `settings.js` to "debug". 
Would it be better to set the verbose logging level to "trace"?

**Comment by 586837r** [comment]
Oh i see what you are talking about!

**Comment by 586837r** [comment]
Those things were never supposed to be logged in a release version, will be fixed in 3.10.1!
