### ISSUE TITLE
ssml sounds (still a limitation?) how about more sounds?

### ISSUE THREAD

**Issue by zimmer62** [586837r/node-red-contrib-alexa-remote2#132]
Thanks for the Sound feature, right now it does seem limited to the sounds you can select from the dropdown list.

What about letting us put in the sound name:
Example:

![image](https://user-images.githubusercontent.com/3384127/81858358-9ee58700-9531-11ea-8cd9-77800f07abe3.png)

The ideal method would be embedding the sound in the SSML, however this could still work pretty well as a stop gap.

**Comment by 586837r** [comment]
I don't prevent you from entering a custom sound id. You can already do that as you have shown.
It looks like Alexa only supports the sounds you can select in the Alexa app which are the ones in the dropdown.
