### ISSUE TITLE
no communication with Sonos One gen1&2, and no error message

### ISSUE THREAD

**Issue by ThomasLoeffel** [586837r/node-red-contrib-alexa-remote2#138]
Hallo Zusammen,

ich habe meinen Flow vor ca. 5 Monaten zuletzt getestet und meine Alexa Geräte sowohl mein Sonos ließen sich perfekt ansteuern. Nun wollte ich heute anfangen das System fertigzustellen und musste feststellen das die Sonosgeräte sich nicht mehr ansteuern lassen. Gefunden werden sie allerdings in der Übersicht. Über Alexa selbst lassen sich die Geräte sich verknüpfen.

Mein System:
- Asus Tinker+
- RaspberryMatic: 3.51.6.20200420
- Redmatic: Version 5.5.3
- Node Version: 3.10.0
- Sonos Version: 11.1

Wie kann ich Dir weiter helfen den Fehler einzugrenzen?
Alexa Echo Geräte spielen alles ab. Sonos nicht.

Gruß Thomas

 
Hello everyone

I last tested my flow about 5 months ago and my Alexa devices both my Sonos could be controlled perfectly. Now I wanted to start finishing the system today and had to realize that the Sonos devices can no longer be controlled. However, they are found in the overview. The devices can be linked via Alexa itself.

My system:

- Asus Tinker+
- RaspberryMatic: 3.51.6.20200420
- Redmatic: Version 5.5.3
- Node Version: 3.10.0
- Sonos Version: 11.1

How can I help you narrow down the error?
Alexa Echo devices play everything. Sonos doesn't.

Greeting Thomas

![grafik](https://user-images.githubusercontent.com/44590735/83950259-b579b800-a829-11ea-8e18-f482112b46d2.png)

![grafik](https://user-images.githubusercontent.com/44590735/83950255-a4c94200-a829-11ea-97ac-26c0b6a78dcf.png)

**Comment by pascalmattes** [comment]
I can confirm this issue. I can't control my Sonos One. My Echo Dot is working just fine.

**Comment by ThomasLoeffel** [comment]
Zusatz:
Auch nach dem Sonos Update auf Version 11.2, hat sich nichts verändert. Kein Sonos Gerät ist ansteuerbar. Im Flow wird alles als "OK" angezeigt.

Gruß Thomas

**Comment by pascalmattes** [comment]
I think you should write in english so everybody can understand especially @586837r

**Comment by ThomasLoeffel** [comment]
Hello Pascal,

Done.

Greetings Thomas

**Comment by ThomasLoeffel** [comment]
Dear all,

in my system is this topic still open. Somebody have the same problem?

Grettings Thomas

**Comment by medaller** [comment]
Hallo Thomas, ja ich hab das Problem auch... schade das hier nichts passiert

**Comment by ThomasLoeffel** [comment]
Dear all,

I dont know really why, but it works now. So I am happy.

My system:
    Asus Tinker+
    RaspberryMatic: 3.51.6.20200621
    Redmatic: Version 6.0.2
    Node Version: 3.10.4
    Sonos Version: 12.0.5

Greetings Thomas
