### ISSUE TITLE
Amazon whines that cookies are not enabled

### ISSUE THREAD

**Issue by jcwren** [586837r/node-red-contrib-alexa-remote2#139]
Stopped working again today. After connecting to localhost:3456 and logging in to Amazon, the browser is returning the attached error. I've tested this under Chrome, Brave, Opera, and IE, all having the same result. Attempted redploying all flows, stopping and restarting NodeRed, no difference.

![image](https://user-images.githubusercontent.com/529578/84311188-e0695200-ab30-11ea-9de6-73db46f14c31.png)

**Comment by elchanly** [comment]
Same here

**Comment by elchanly** [comment]
I managed to solve it. What i did: I tried to configure haaska on an account but couldnt finish. I did it with another but haaska kept there. Deleting this made it. Maybe it has something to do with that urls you have to put into there.

**Comment by jcwren** [comment]
> I managed to solve it. What i did: I tried to configure haaska on an account but couldnt finish. I did it with another but haaska kept there. Deleting this made it. Maybe it has something to do with that urls you have to put into there.

I don't know what this means. What is 'haaska' and what were you deleting that made it work?

**Comment by scrhall** [comment]
Same here (alexa.amazon.es)

**Comment by elchanly** [comment]
Haaska is a "brigde" between Home Assistant and Alexa, so Alexa can invoke HomeAssistant entities.

What is important in this is I suspected that this had to do something with that error. So i got into amazon developer console, deleted skill and got node red module back.
In this case, im sure it has to be related to redirect URLs involved there. If you have been playing with developer console, this could be your case.

**Comment by poldy82** [comment]
Same here.
The only way I managed to get the node running, was to change the authorization method to username & password instead of using cookies.

**Comment by scrhall** [comment]
I used the cookie method getting the cookie with chrome

**Comment by samuelMeddows** [comment]
> 
> 
> I used the cookie method getting the cookie with chrome

How were you able to get the cookie?
I am having the same issue. I'm using Node-Red stand alone without House Assistant.

**Comment by scrhall** [comment]
> > I used the cookie method getting the cookie with chrome
> 
> How were you able to get the cookie?
> I am having the same issue. I'm using Node-Red stand alone without House Assistant.
I follow this instructions:
https://github.com/586837r/node-red-contrib-alexa-remote2/blob/master/get_cookie.md

**Comment by maxweb80** [comment]
same problem here, anyone solved it?

**Comment by dedelajoie** [comment]
> 
> 
> > > I used the cookie method getting the cookie with chrome
> > 
> > 
> > How were you able to get the cookie?
> > I am having the same issue. I'm using Node-Red stand alone without House Assistant.
> 
> I follow this instructions:
> https://github.com/586837r/node-red-contrib-alexa-remote2/blob/master/get_cookie.md
I didn't manage to get it work : I cannot find a "queue-and-play request" when using the amazon.com account linked to my amazon dot (but I can find it using with my echo linked to my amazon.fr account)(but I don't want send messages on this device).
Anyone else got a clue ?

**Comment by andyuk5** [comment]
Hi All 
same problem here, Im using a raspberry pi and get same error as above.
But I can log in to my amazon account using the browser on raspi.
Anyone got anymore ideas what this is please.

**Comment by andyuk5** [comment]
hi all

sorry but i can not see any radio station to pick.
can someone help with this as I love to get it working.

**Comment by jcwren** [comment]
Looks like 3.10.3 fixed it. Thanks!

**Comment by andymk3** [comment]
Not working for me on 3.10.4.

Working with the cookie method though.

**Comment by bwims** [comment]
Anybody else get the feeling that this is abandonware?

**Comment by andymk3** [comment]
> Anybody else get the feeling that this is abandonware?

Starting to feel that way.
