### ISSUE TITLE
Handling of spoken numbers

### ISSUE THREAD

**Issue by coppo86** [586837r/node-red-contrib-alexa-remote2#15]
I cannot find a way of making Alexa handle numbers correctly in all cases. If I enter a decimal such as 22.2 alexa will say 22 comma 2, ignoring whatever punctuation character I put there. The work around is I substitute the word point for the DP. I couldn't find any other way of getting this to work.

I also think the interpretation of time ins a string is variable (possibly context sensitive).
I now can have a message such as this "Completed at 22:54" and Alexa will announce as expected. A bit earlier  I had a similar but subtly different string and Alexa would announce the time as 2 thousand 2 hundred and fifty four.

I tried using the Alexa speech markup SSML but she simply spoke the contents as normal text, ignoring the  headers.
Is there any way of forcing numbers to be spoken as intended?
Coppo

**Comment by 586837r** [comment]
The library was replacing dots with commas. That now no longer happens. (version 3)
Please check out the example for how you can get ssml to work.
