### ISSUE TITLE
msg.payload.description.summary property is now blank

### ISSUE THREAD

**Issue by quadhammer** [586837r/node-red-contrib-alexa-remote2#151]
I was using https://community.home-assistant.io/t/approaches-to-room-aware-voice-commands-for-alexa-with-node-red/165399 as a means to turn on different devices based on Alexa location, but just recently the summary property no longer lists what was said, but just "".

Is this something Amazon has done, or perhaps an unexpected change to the node?

Thanks

**Comment by ftsguy** [comment]
Same issue with me i noticed if i issue anything with set or turn off/on its blank

**Comment by quadhammer** [comment]
@ftsguy When did this start for you?  Have you recently updated the node via the palette?

**Comment by ftsguy** [comment]
Well i didn't update when it stopped working but updated just to see if it would fix it and it still didn't work. Based on the logs im seeing in the past i think i was getting 2 events triggering one with the summary populated and one without but now im only getting one thats blank. My guess is turn on/off, set commands are not sending over now on the activity feed which really sucks.

**Comment by ftsguy** [comment]
If i say mute the TV that i have setup as a routine it works. seems the smart home commands are whats impacted.

**Comment by ftsguy** [comment]
Well interesting i didnt change anything and  looks like they are coming in now @quadhammer working for you now as well ?

**Comment by quadhammer** [comment]
Yes, @ftsguy my summary is working again now with things like "turn on the lights"!

Bizarre.  Hope it's not a regular malady.

**Comment by ftsguy** [comment]
@quadhammer agree a little concerning it took my whole house down lol

**Comment by quadhammer** [comment]
I hear that! :)  It was a mad dash yesterday to get something cobbled together as an alternative.  

As I said in another thread: I ended up monitoring payload.name, and using a node red switch to fire off an MQTT event for that particular room, which then enabled an EventGhost folder with that room name for 10 seconds, and then disabled it. The same device event ( lights, fan, aircon et cetera) was retriggered after a few seconds with a off/on, but only the enabled folder for that room.

It worked pretty well actually.  I might even do the same thing using input_boolean switches in Home Assistant for each room with an Echo.  The first invocation, (Alexa), would turn that virtual room switch 'on', and then the second one, (turn on whatever), would just need to use a 'current state node' to check which room was on.

I'm not sure how I would do a delay and trigger, if it was said all in one invocation though...

**Comment by Cjkeenan** [comment]
Is this still an issue because room aware commands using the event node is working fine for me while looking at the summary for content of what was said.

**Comment by quadhammer** [comment]
> Is this still an issue because room aware commands using the event node is working fine for me while looking at the summary for content of what was said.

Yes, it's working again now, and has been for 3 months, or so.
