### ISSUE TITLE
How to save Cookie info using Proxy method

### ISSUE THREAD

**Issue by whitwhittle** [586837r/node-red-contrib-alexa-remote2#172]
I saw this asked previously, but the issue appeared to be closed without a real resolution....

I have attempted multiple ways to save the cookie information using the PROXY method, but apparently, I am not entering the correct information in the File field.

I have tried on both a Docker implementation AND a straight install on Ubuntu 18.04, have created directories, used full path names, etc.  A previous response indicated that you had to reference a file and not just a path, but how do you have a file without the "cookie"?  Really want to use this, but don't want to have to authenticate everytime I re-deploy...

EISDIR: illegal operation on a directory, read
initialising "Alexa Node-Red" with the PROXY method and NO saved data....

Have also seen ENOENT: no such file or directory.. (when in fact, there IS a directory...)

Thanks,

**Comment by hajtux** [comment]
Hello all, I have the same problem as whitwhittle. 
Could you please help ?
In advance thanks !

**Comment by whitwhittle** [comment]
Actually, I have mine working now (meant to come back and update...)

Instead of trying to enter a path, I simply put in a file name (I used **_auth_**).  After deploying, a 2nd time, the authorization happended automatically, and I was able to continue on...

**Comment by iyashwant** [comment]
hi @whitwhittle , did you give any file extension? or did you just enter auth in the file path ?
I'm running homeassistant and I installed node-red from the hassio store, so i'm not able to access the root of my pi to create folder, can you explain little more about how you solved it, i entered just the file name auth in file path but i get ENOENT: no such file or directory, open 'auth'
