### ISSUE TITLE
How work "Set SmarthomeEntities" ?

### ISSUE THREAD

**Issue by ddinternetagentur** [586837r/node-red-contrib-alexa-remote2#18]
Is it possible synonymous devices that are connected only in echo via a node to control ??

I have 1-2 lamps from China which are only connected in the echo ..

I found only the get function but no set to send states or colors

**Comment by 586837r** [comment]
You can't do this directly but you can create Routines in your alexa app and execute them with the Action node and `executeAutomationRoutine`.

**Comment by 586837r** [comment]
woops, scratch that, next update will have a way to do this

**Comment by ddinternetagentur** [comment]
Where is the Update ? ;-) i dont't find this future 💃

**Comment by 586837r** [comment]
That got delayed :/. I'm working on version 3.0.0 that will have an interface overhaul along with an easy way of controlling smarthome devices. Not sure when its ready yet...

**Comment by 586837r** [comment]
Controlling Smarthome devices is now possible with an *Alexa Smarthome* node or an *Alexa Routine* node! (version 3.0.0)
