### ISSUE TITLE
Speak at volume doesnt change volume

### ISSUE THREAD

**Issue by nappyjim** [586837r/node-red-contrib-alexa-remote2#182]
Tried it on 2 Echo 3rd gens.  Set volume from anywhere from 10 to 100 and it does not change the actual volume when Alex speaks.

![image](https://user-images.githubusercontent.com/71914301/102725630-d2656c80-42dd-11eb-8adb-c5017fc2bd21.png)

**Comment by nappyjim** [comment]
But if I do a separate volume node then a speak node, it does respond accordingly...

![image](https://user-images.githubusercontent.com/71914301/102726172-0f336280-42e2-11eb-8f5e-4340b7937f7f.png)

**Comment by driagi** [comment]
I have the same problem. I had opened an issue #177 (after closed), then it started working. Honestly, it seems that a little bit works and a little bit doesn't.

**Comment by nappyjim** [comment]
@driagi , I feel like it did work for me too, the first time I tried it.  But since then, I haven't gotten it to work again unless I add the volume node in front of the speak node.

Come to think of it, the time it did work, I believe I was playing a radio station thru the echo at a low volume and then when I sent the speak node at volume 50,  it worked.

**Comment by rdsubhas** [comment]
@nappyjim @driagi I powered off and powered on the affected device, and it started working!

I had the same issue as well. Speaker group with 3 devices, but only 2 changed volume. But after powering off/on the 3rd device, it also set the volume correctly. Not sure if this is permanent or temporary though.

### Update

Nope, not permanent. After 1 day it stopped working. Had to restart the echo again.

**Comment by 877dev** [comment]
Same issue happening for me too...

**Comment by hannoverRed** [comment]
bei mir geht es auch nicht

**Comment by f4bio79** [comment]
> Tried it on 2 Echo 3rd gens. Set volume from anywhere from 10 to 100 and it does not change the actual volume when Alex speaks.
> 
> ![image](https://user-images.githubusercontent.com/71914301/102725630-d2656c80-42dd-11eb-8adb-c5017fc2bd21.png)

**do not use REGULAR, try with the ANNOUNCEMENT and it will work!**

**Comment by MarkusBe** [comment]
Same thing here. Any Ideas?

**Comment by f4bio79** [comment]
> Same thing here. Any Ideas?

do not use REGULAR, try with the ANNOUNCEMENT and it will work!

**Comment by MarkusBe** [comment]
I tried it, nothing happened. But when I changed it back to "regular", everything was working fine again! Until now it doesn't matter if I use "regular" or "announcement", it is working with both settings. Kind of weird behavior... 

Anyway, thanks for answering!

**Comment by BigWalnutZ** [comment]
My `Announcement` setting is not changing the volume.  The `Regular` is changing the volume.  Go figure...  Any moves on this yet?

**Comment by BigWalnutZ** [comment]
So, does that mean this is resolved?  There are no notes since my last comment.
