### ISSUE TITLE
Authentication fails periodically

### ISSUE THREAD

**Issue by ThomasPoett** [586837r/node-red-contrib-alexa-remote2#19]
Hi,
I use remote2 for announcements with Alexa. But figured out the following issues:
if cookie auth is used (with/ or without pwd), after cookie timedout -> Auth failed until new cookie will be set
if pwd based only, it fails and requires web-based authentication with e.g. SMS
this issue occurs periodically after approx. 10-14 days (haven't measured is exactly).

If cookie was provided, reenter pwd will fix it for another 14 days, than cookie will be required because of web-auth is needed or I get a new cookie in.

I haven't have any idea how to solve this issue. Guess there might be another setting in Alexa changing some timeouts. Has anyone a similar problem or even found a work-a-around which so not require continuously provide a new cookie/ or permantly set the user/pwd?

**Comment by 586837r** [comment]
I exposed logging in via proxy of the underlying library in version 2.0.0. You can refresh cookies now. Let me know if it works!

**Comment by ThomasPoett** [comment]
I'm still testing, and found an issue @586837r 
the Init notes tells me login to IP:3456, the Alex login page appears, urs/pwd is provided.
next message /cookie-success is displayed in the browser.
next the node shows login unsuccessful :(
I've tried with/without the combination of home and user agent.
still the same result - login unsuccessful.
(using the "old" cookie way works, but the time runs out (cookie validity)
If you need further info/data/logs let me know.

**Comment by 8xiom** [comment]
Same here like @ThomasPoett described. Surprisingly the proxy method worked in the first place, although I didn't provide a path in order to store the underlying cookie. After two or three days the account needed to be reconfirmed but then I got the "No csrf" error. Switching to the cookie method helped - for the moment.

**Comment by ThomasPoett** [comment]
Since this morning having the same error as @8xiom : No CSRF

**Comment by derekoharrow** [comment]
> Since this morning having the same error as @8xiom : No CSRF

Me too - No CSRF.

I've tried moving to username/password (on Node v10) and same - No CSRF

**Comment by Prog72** [comment]
> Since this morning having the same error as @8xiom : No CSRF

Same for me unfortunately. Have Amazon changed something?

**Comment by 8xiom** [comment]
It seems that Amazon indeed changed something. Bear with me for not going into detail here since I unfortunately do not have the skills which are necessary to analyse this.
After doing some searches I found that the user @thorsten-gehrig patched his own tool to cope with this change by Amazon. Please see the latest change for his tool at https://github.com/thorsten-gehrig/alexa-remote-control.
Hopefully somebody is able to transfer his change to this project.

**Comment by 586837r** [comment]
This project uses [alexa-remote](https://github.com/Apollon77/alexa-remote). The author is already working on a fix, and will release it soon. I will update the dependency as soon as the new version is available.

**Comment by 586837r** [comment]
Should work again in version 2.3.0!

**Comment by RedCross0815** [comment]
Hello its me again, and iam hving the problem again: "no json". It seems that the refresh works properly, but after a refresh the sequenze node says "no json".. :(
Does yours work?

![Bild](https://user-images.githubusercontent.com/45964713/61740423-e62a3d80-ad8e-11e9-83e9-db1394792c19.JPG)

**Comment by ThomasPoett** [comment]
> Hello its me again, and iam hving the problem again: "no json". It seems that the refresh works properly, but after a refresh the sequenze node says "no json".. :(
> Does yours work?
> Did i made something wrong?

Mine working fine and stable now.
Just had one issue after reboot, i needed to key in the credentials again. (But thats ok)

**Comment by 8xiom** [comment]
> > Hello its me again, and iam hving the problem again: "no json". It seems that the refresh works properly, but after a refresh the sequenze node says "no json".. :(
> > Does yours work?
> > Did i made something wrong?
> 
> Mine working fine and stable now.
> Just had one issue after reboot, i needed to key in the credentials again. (But thats ok)

Similar here. I too had the "no json" error but after stopping and restarting the docker container (my Node Red installation runs dockerized on a Raspi 3B+) it was working.
