### ISSUE TITLE
My list of Routines disappeared!

### ISSUE THREAD

**Issue by bwims** [586837r/node-red-contrib-alexa-remote2#192]
I have a number of routines, and I have been quite happily using Execute routine until today when the complete list disappeared from Alexa-Remote2.  All I see are 3 question marks.

Any ideas?

Thanks!

**Comment by artgreen** [comment]
I see similar stuff with my set up.  Suggest you read other issues on this repo and you'll see that all kinds of things are breaking with these nodes.  So, it's probably not you alone.  (Everything was working for a long time and now... dead, right??) ;)

**Comment by bwims** [comment]
Oh dear!  Is this going to be abandonware?   I really love these routines.  Probably bloody Amazon, changing everything every 5 minutes with minimal notification!

**Comment by datbilling** [comment]
Mine are missing today too.

**Comment by GaryStimson** [comment]
Check out the other thread, there is a workaround that some have working (currently not working for me though :( ):
[https://github.com/586837r/node-red-contrib-alexa-remote2/issues/191](url)

**Comment by l19mxb** [comment]
Following This too, All my routines have now disappeared and replaced with "???"

I have restarted the service, rebooted the Pi then refreshed the Authentication Cookie then initialized. 

Still no luck


![image](https://user-images.githubusercontent.com/49220201/106371943-c7aef480-63be-11eb-8b82-dabffe42dba2.png)

**Comment by felipesdreis** [comment]
my routines are gone too 

error:
[alexa-remote-account:xxxxxxxxxxx] failed to load routines: "no body"

**Comment by bwims** [comment]
I got mine working, using this https://github.com/586837r/node-red-contrib-alexa-remote2/issues/191#issuecomment-769019376

NOTE however, that different OSs and versions of Node-Red install into different locations.

See here:

https://github.com/586837r/node-red-contrib-alexa-remote2/issues/191#issuecomment-769757823

**Comment by bwims** [comment]
All of this is dealt with under https://github.com/586837r/node-red-contrib-alexa-remote2/issues/191
