### ISSUE TITLE
"failed to load routines: "routines.map is not a function""

### ISSUE THREAD

**Issue by MonkeyBusiness1** [586837r/node-red-contrib-alexa-remote2#196]
I have a refresh cookie flow that fires on a regular interval.

A new cookie is successfully downloaded, but the following error is thrown...

"failed to load routines: "routines.map is not a function""

Has anyone else noticed this issue which started after I performed the @cakebake update?

I am on a Windows 10 machine with latest releases of npm and node red, and the cakebake update.

I had the "no body" error until I did the @cakebake update in #191 and then this new error presented.

**Comment by obaldius** [comment]
It's so sad this node is falling apart.. I really hope some dev comes save it. I'd be happy to donate.

**Comment by MonkeyBusiness1** [comment]
For me I am most grateful to the likes of @cakebake for their great efforts on this node.  Yes, there are still some issues, but he and others have contributed selflessly to tweak it to a point where we have the necessary functionality back.  I think my problem is an outlier and even with the error, everything still works for me.  So do follow issue #191 as that's where the real substantial help is coming from!

**Comment by MonkeyBusiness1** [comment]
I discoverd that this error occurs when there are no Alexa routines...

I simply created a dummy routine and the error is no longer there!

**Comment by quadhammer** [comment]
> I discoverd that this error occurs when there are no Alexa routines...
> 
> I simply created a dummy routine and the error is no longer there!


Just to be clear, do you need to make a routine in the Alexa app, rather than one in node red, for the issue to disappear?

**Comment by MonkeyBusiness1** [comment]
Sorry for the late reply, but the routine was made in the alexa routine in the app.

A simple announcement on saturday to listen to our favorite podcast!
