### ISSUE TITLE
How to send to multiple devices

### ISSUE THREAD

**Issue by BassTeQ** [586837r/node-red-contrib-alexa-remote2#20]
If I want to control or send TTS to multiple devices, does this require an "alexa sequence" for each device?

**Comment by ThomasPoett** [comment]
Hi you can actually do it in two ways. Either lopping and sending the Alexa device name, else you connect a function node to multiple device

**Comment by BassTeQ** [comment]
Could you share a screenshot of such examples?

Thanks

**Comment by NovaGL** [comment]
@BassTeQ  I'm using this node to resend the msg.
https://flows.nodered.org/node/node-red-contrib-msg-resend

Then a switch node with msg.count, so 1 goes to bedroom, 2 goes to kitchen, 3 goes study,

I think that's the easiest way. A function node does similar but this way uses less code.

**Comment by BassTeQ** [comment]
Thanks @NovaGL will give this a try!

**Comment by ThomasPoett** [comment]
![image](https://user-images.githubusercontent.com/43953071/59248048-86823380-8c21-11e9-8b49-e708733de4e7.png)
sure it could look like this

**Comment by BassTeQ** [comment]
Every time I deploy my flow I have to re-authenticate, is this expected behaviour?

**Comment by NovaGL** [comment]
I have that too. Store a cookie in a file that way it won't re-authenticate it will just use the cookie.

I'm using a init node and it seems to work.

**Comment by BassTeQ** [comment]
@NovaGL , this is what I have at the moment, have I missed something?
Using an sequence for each device, should I be using an init node instead?

<img width="727" alt="flow" src="https://user-images.githubusercontent.com/32693997/59423957-80a17380-8e16-11e9-8d83-f0029c3f1fd5.PNG">

Thanks

**Comment by NovaGL** [comment]
Your problem is file path is a file not a folder.

**Comment by ThomasPoett** [comment]
do you run node-red on windows? if not and its raspi, use the Linux notation.
but I still have an issue with (cannot authenticate) with proxy. still figuring out whats going on

**Comment by NovaGL** [comment]
@ThomasPoett I'm using a Pi2. What happens when you try to authenticate, connect it to a debug node and does it have output

**Comment by BassTeQ** [comment]
@NovaGL  Thanks, I've changed it to C:\temp\node-red\cookie.txt and its working now :)
Is there any benefit to using an 'init' node?
Do I also need to have a flow that does a cookie refresh? If so how would this be done?

@ThomasPoett , yes I'm running on windows.

**Comment by NovaGL** [comment]
Cookie refresh is done in the init node using a payload of refresh.

So I guess that answers both your questions :)

**Comment by ThomasPoett** [comment]
> @ThomasPoett I'm using a Pi2. What happens when you try to authenticate, connect it to a debug node and does it have output

its the message of cookie file doesn't exitis, I guess this is a wrong path with my PI3

**Comment by BassTeQ** [comment]
> Cookie refresh is done in the init node using a payload of refresh.
> 
> So I guess that answers both your questions :)

Thanks @NovaGL , are you able to share a screenshot?
I've added the init node, how to I pass the payload with a value of refresh?

**Comment by NovaGL** [comment]
Looks right to me. I would try 48hrs not sure how long the cookie lasts

**Comment by ThomasPoett** [comment]
the cookie lasts approx. 8 days. but sure refresh every 24hrs and trace the response can be help full. I'll trace the response every 24 hrs and write it to dashboard

**Comment by BassTeQ** [comment]
Any idea why I'm getting this "no JSON" error appearing?
The payload is coming from an MQTT Topic, I'm setting it to "this is a test"
Thanks
![image](https://user-images.githubusercontent.com/32693997/59576876-9fe51d00-9104-11e9-85f9-5d996d793774.png)

**Comment by NovaGL** [comment]
Has the cookie expired?

**Comment by BassTeQ** [comment]
No, if I re-deploy the flow, it goes to a "ready" state.

**Comment by NovaGL** [comment]
So other commands, like get devices work?

**Comment by BassTeQ** [comment]
I've not used that one before, will add it.

**Comment by BassTeQ** [comment]
Yes get devices works fine

![image](https://user-images.githubusercontent.com/32693997/59581090-18ed7000-9117-11e9-827a-f2891054ebcf.png)

**Comment by BassTeQ** [comment]
Things seem to be working ok for the time being, will monitor.

Do you know if its possible to get the current volume from a device?
I'd like to set the volume, read the text to speech and set the volume back to its original value.

Cheers

**Comment by NovaGL** [comment]
Pretty sure you can set device actions not at a PC to check
 Just look at the various nodes.

**Comment by BassTeQ** [comment]
I cant find anything obvious to obtain the volume level within the "Alexa Get" node

**Comment by NovaGL** [comment]
The examples might help.
https://github.com/586837r/node-red-contrib-alexa-remote2/blob/85ecb370e638f59678c3e7dc005a17ad2d48b8a7/examples.md

**Comment by BassTeQ** [comment]
Thanks, so I want to look at example 3, to see how it works.
I have the dashboard installed, how do I create one using a json string?
Eg;
[{"id":"d88ff07e.1817a","type":"tab","label":"Alexa Music","disabled":false,"info":""},{"id":"85ce383c.682918","type":"ui_dropdown","z":"d88ff07e.1817a","name":"","label":"Provider","place":"    ***SNIP***

**Comment by NovaGL** [comment]
Just look at the nodes not the output. You might get overwhelmed otherwise

**Comment by BassTeQ** [comment]
Spoke too soon, now getting an error "no csrf"
I've removed the cookie, re-authenticated, and still see this error.

![image](https://user-images.githubusercontent.com/32693997/59661985-59b8b800-91ef-11e9-8d5f-86f7a4b4ae9a.png)

**Comment by NovaGL** [comment]
Delete the cookie and re-authenticate should work.

Use Alexa command to set the volume. Will edit this post if I can find the original value

**Comment by 586837r** [comment]
@BassTeQ 
- **no JSON** means that you get an invalid response from amazon. This happens when something is wrong with your cookie.
- I'm currently also getting "no JSON" and "no csrf found" errors when using the proxy method. Manual cookie still works...
- You can get the volume with get media (this is not in the examples), so to set the volume to the original value you can do this: 
```
[{"id":"cbdf4c36.0296a","type":"alexa-remote-get","z":"c7058271.2790f","name":"","account":"","target_type":"select","target_value":"media","serialOrName_type":"str","serialOrName_value":"","options":{"devices":{},"cards":{"limit":{"type":"num","value":"10"},"beforeCreationTime":{"type":"str","value":"%t"}},"media":{},"playerInfo":{},"list":{"size":{"type":"num","value":"100"},"startTime":{"type":"str","value":""},"endTime":{"type":"str","value":""},"completed":{"type":"bool","value":"false"},"listType":{"type":"select","value":"TASK"}},"wakewords":{},"notifications":{"cached":{"type":"bool","value":"true"}},"doNotDisturb":{},"deviceNotificationState":{},"bluetooth":{"cached":{"type":"bool","value":"true"}},"activities":{"startTime":{"type":"str","value":""},"size":{"type":"num","value":"1"},"offset":{"type":"num","value":"1"}},"account":{},"conversations":{"latest":{"type":"bool","value":"true"},"includeHomegroup":{"type":"bool","value":"true"},"unread":{"type":"bool","value":"false"},"modifiedSinceDate":{"type":"str","value":"1970-01-01T00:00:00.000Z"},"includeUserName":{"type":"bool","value":"true"}},"automationRoutines":{"limit":{"type":"num","value":"2000"}},"musicProviders":{},"homeGroup":{},"devicePreferences":{},"smarthomeDevices":{},"smarthomeGroups":{},"smarthomeEntities":{},"smarthomeBehaviourActionDefinitions":{}},"x":330,"y":740,"wires":[["297f0996.343656"]]},{"id":"280eeef7.485c92","type":"inject","z":"c7058271.2790f","name":"","topic":"","payload":"","payloadType":"date","repeat":"","crontab":"","once":false,"onceDelay":0.1,"x":160,"y":740,"wires":[["cbdf4c36.0296a"]]},{"id":"297f0996.343656","type":"alexa-remote-sequence","z":"c7058271.2790f","name":"","account":"","serialOrName_type":"str","serialOrName_value":"","sequenceInputs":[{"command":"volume","value_type":"num","value_value":"50"},{"command":"speak","value_type":"str","value_value":"Hello World!"},{"command":"volume","value_type":"msg","value_value":"payload.volume"}],"x":520,"y":740,"wires":[[]]}]
```

**Comment by BassTeQ** [comment]
Tried deleting the cookie, re-authenticated, but still seeing the error.

@586837r , I've tried using the content of the cookie with the "cookie" method, but it says authentication failed, should I be using the whole content of the cookie.txt or just part of it?

The code you pasted to set to the original volume, how would I use that?
I currently have an "alexa sequence" where I set the volume, speak the text, then I'd like to reset the volume to the original value.

Cheers

**Comment by NovaGL** [comment]
That looks correct assuming you stored the volume before in that payload (from get media)

**Comment by BassTeQ** [comment]
@NovaGL I'm actually passing a volume value in the json via mqtt in that screenshot, its not from the device.

How do  I use the code below to create a node?
`[{"id":"cbdf4c36.0296a","type":"alexa-remote-get","z":"c7058271.2790f","name":"","account":"","target_type":"select","target_value":"media","serialOrName_type":"str","serialOrName_value":"","options":{"devices":{},"cards":{"limit":{"type":"num","value":"10"},"beforeCreationTime":{"type":"str","value":"%t"}},"media":{},"playerInfo":{},"list":{"size":{"type":"num","value":"100"},"startTime":{"type":"str","value":""},"endTime":{"type":"str","value":""},"completed":{"type":"bool","value":"false"},"listType":{"type":"select","value":"TASK"}},"wakewords":{},"notifications":{"cached":{"type":"bool","value":"true"}},"doNotDisturb":{},"deviceNotificationState":{},"bluetooth":{"cached":{"type":"bool","value":"true"}},"activities":{"startTime":{"type":"str","value":""},"size":{"type":"num","value":"1"},"offset":{"type":"num","value":"1"}},"account":{},"conversations":{"latest":{"type":"bool","value":"true"},"includeHomegroup":{"type":"bool","value":"true"},"unread":{"type":"bool","value":"false"},"modifiedSinceDate":{"type":"str","value":"1970-01-01T00:00:00.000Z"},"includeUserName":{"type":"bool","value":"true"}},"automationRoutines":{"limit":{"type":"num","value":"2000"}},"musicProviders":{},"homeGroup":{},"devicePreferences":{},"smarthomeDevices":{},"smarthomeGroups":{},"smarthomeEntities":{},"smarthomeBehaviourActionDefinitions":{}},"x":330,"y":740,"wires":[["297f0996.343656"]]},{"id":"280eeef7.485c92","type":"inject","z":"c7058271.2790f","name":"","topic":"","payload":"","payloadType":"date","repeat":"","crontab":"","once":false,"onceDelay":0.1,"x":160,"y":740,"wires":[["cbdf4c36.0296a"]]},{"id":"297f0996.343656","type":"alexa-remote-sequence","z":"c7058271.2790f","name":"","account":"","serialOrName_type":"str","serialOrName_value":"","sequenceInputs":[{"command":"volume","value_type":"num","value_value":"50"},{"command":"speak","value_type":"str","value_value":"Hello World!"},{"command":"volume","value_type":"msg","value_value":"payload.volume"}],"x":520,"y":740,"wires":[[]]}]`

**Comment by NovaGL** [comment]
By node I mean variable. You can use the change node to store the value or store in a global or flow variable.

**Comment by 586837r** [comment]
@BassTeQ 
- Open the top right menu in node-red, *Import*->*Clipboard* and paste the code in and import
- The cookie method does not work with the content of the file that has been created with the proxy method. To manually get the cookie to paste into the cookie field see [get_cookie.md](get_cookie.md)

**Comment by BassTeQ** [comment]
Thanks @NovaGL  and @586837r , will try out your suggestions and see how it goes.

Any idea why the proxy method is no longer working? Not ideal to use the cookie due to the expiry,

**Comment by 586837r** [comment]
Yeah, it seems something changed with amazon. Other users of the underlying library have reported the same error. `https://github.com/Apollon77/alexa-remote/issues/44`

**Comment by BassTeQ** [comment]
Thanks for confirming, I have the cookie working now, and I've included your example, just trying to get it working in my flow.

Cheers

**Comment by BassTeQ** [comment]
I've created this, now a little stuck.

![image](https://user-images.githubusercontent.com/32693997/59743345-42db9980-92b3-11e9-9885-9f100261418a.png)

In the inject node I pass a json string 
```
{ "text": "this is some test", "volume_before" : "50" }
```
In the commands, the highlighted ones come from the JSON payload, and the 3rd comes from "get media kitchen". It appears the payload is missing the values from the JSON, how should these be injected?

Cheers

**Comment by NovaGL** [comment]
Volume before should be a number and doesn't need quotes.

You can use the change node.
![image](https://user-images.githubusercontent.com/16315601/59756349-e4231980-92cc-11e9-898b-63d063f947d5.png)

Then use this 
![image](https://user-images.githubusercontent.com/16315601/59756399-fac97080-92cc-11e9-85dc-cb55f4649429.png)

**Comment by BassTeQ** [comment]
Thanks @NovaGL  will try out your suggestion.

**Comment by BassTeQ** [comment]
> Yeah, it seems something changed with amazon. Other users of the underlying library have reported the same error. `https://github.com/Apollon77/alexa-remote/issues/44`

Reading that thread, it appears they've now fixed it, hope it gets included here soon!

**Comment by 586837r** [comment]
You're right! It should work again in version 2.3.0

**Comment by ThomasPoett** [comment]
Mhhh, either I'm not clever enough or there is still an issue with Proxy Auth.
Cookie works within the limitation to TTL, but Proxy has an issue with now Auth fail.
![image](https://user-images.githubusercontent.com/43953071/59963671-b3262d00-94f6-11e9-9f73-9c3b12fa515e.png)
![image](https://user-images.githubusercontent.com/43953071/59963680-cfc26500-94f6-11e9-96d3-b6427bb02c7f.png)
it running on rapsmatic…

**Comment by 586837r** [comment]
There is nothing wrong with your configuration.
Some ideas if you haven't done that already: 
- delete the old file in the file path
- use your browsers icognito mode when logging in via proxy

**Comment by ThomasPoett** [comment]
it is a little wired, there was no file stored and uppon i used icognito mode I got this error from the node: "Error: EISDIR: illegal operation on a directory, read"

**Comment by 586837r** [comment]
The first error is because a path to a file is expected like `/usr/test01/alexa-cookie.json`, not a directory.
But authentication should still work.
Looks like there is something wrong with the proxy on your system.
As a workaround I suppose you could generate the file on a different system and copy it over.

**Comment by ThomasPoett** [comment]
I think I know why… the RaspMatic is different from a "normal" Linux distribution. Therefore the main directories are not writable. So I can create a in e.g. tmp. I also was able to write a file with "vi". Could may post a json example of the cookie file. I'll will copy the actual cookie in and try.
This seems also the problem with Authentication/Proxy, due to the RaspMatic seem to be a little to different. @hobbyquaker who ported Node-Red might be the right one helping out with this issue

**Comment by 586837r** [comment]
This *File Path* option is just an extra feature that automatically saves some data from the result of the authentication. It should not affect the success of the authentication!

The result of the Proxy authentication is not just the cookie, it looks something like this:
```
{
    "loginCookie": "...",
    "frc": "...",
    "map-md": "...",
    "deviceId": "...",
    "deviceSerial": "...",
    "refreshToken": "...",
    "tokenDate": 1234,
    "amazonPage": "...",
    "localCookie": "...",
    "csrf": "..."
}
```

I don't think there is a way to fill this manually.

Also note:
You can manually initialise the *Alexa Account* node with a *Alexa Init* node and use it to save that result any way you want, to later initialise the account again with that result.
The *File Path* just does that for you. It can stay blank.

**Comment by ThomasPoett** [comment]
Hi, if i leave the path "undefined" i receive the same error with Auth failed.
Well, seem a little complex getting the json correctly. since its a proxy, maybe i can try "fetcher" it? But it seem to be easier if i run a node-red windows setup and try.

**Comment by BassTeQ** [comment]
Proxy method is working again. I now have a weird issue in this flow.
If I inject a json string it works fine, alexa will speak the text contained in **flow.HSPayload.text**
however populating a mq topic with a json string causes alexa to speak "undefined"

![image](https://user-images.githubusercontent.com/32693997/60090796-8a1bcb80-9786-11e9-8fba-6a946f8ac5a0.png)

Here's my change node
![image](https://user-images.githubusercontent.com/32693997/60090916-cbac7680-9786-11e9-893d-a83978d1f26d.png)

Alexa Sequence
![image](https://user-images.githubusercontent.com/32693997/60090994-f26aad00-9786-11e9-865f-43acf0431055.png)

**Comment by NovaGL** [comment]
That topic does not contain json it is a mqtt path? If that's the only problem add a delete rule for msg.topic.

**Comment by BassTeQ** [comment]
Thanks @NovaGL , does this look right? I'm still hearing "that device wasn't found"

![image](https://user-images.githubusercontent.com/32693997/60091982-2ba41c80-9789-11e9-821b-013964911000.png)

**Comment by NovaGL** [comment]
You'll improve in no time so many shortcuts your code will be half. You only need one change node you can do the delete in that one.

Ok, so I did some testing I don't have a problem with the topics

Try a basic example like this and then build from there to find your problem

Inject node
```json
{
    "speak": "Testing 1 2 3",
    "device": "Echo Dot"
}
```

Alexa Sequence

device = msg.payload.device
speak = msg.payload.speak

Basically what I am saying is define the device name in the message.

For MQTT you can do + as a wildcard or # for a multi-level wildcard

**Comment by BassTeQ** [comment]
Thanks for the tips, much appreciated!

Adding the delete to the existing change node seems to have done the trick :)

![image](https://user-images.githubusercontent.com/32693997/60093300-72dfdc80-978c-11e9-96ea-2887a1570d00.png)

**Comment by ThomasPoett** [comment]
So, @586837r installed Dev System on Windows. with the same result in using the Proxy method.
![image](https://user-images.githubusercontent.com/43953071/60113744-b6c5e800-9772-11e9-906c-5818b71d3425.png) 
![image](https://user-images.githubusercontent.com/43953071/60113809-d3622000-9772-11e9-8c90-fc78bc8b407a.png)

I'm not sure whats acutally going on. its version 2.3.1.
Can I do further logging for you?
I really wanna figure out what causing the issue.

**Comment by 586837r** [comment]
What is 'Dev System' ? Do you just mean that you installed node-red on Windows?

What would be very helpful is creating a minimal example of the error. That  means using alexa-remote2 directly. Try running this script and see if you get an error or `SUCCESS`:
https://gist.github.com/586837r/5f94080c265dd63fa5b9c00a65ca4320

Here is how you can execute it:
 - create a new folder and put this file inside
 - in this folder run `npm install alexa-remote2`
 - in this folder run `node alexa-remote2-test-de.js`

t will prompt you to go to localhost:3456. After that if you see `SUCCESS` then there is clearly something wrong with how I interface with [alexa-remote2](https://www.npmjs.com/package/alexa-remote2). If you get an Error instead then it would make sense to create an issue over there. In that case Apollon77 is more likely to be able help you out.

**Comment by BassTeQ** [comment]
Any idea whats causing this error? The flows just stop working after a period of time.
```
1 Jul 13:49:12 - [info] Started flows
(node:16052) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 status listeners added. Use emitter.setMaxListeners() to increase limit
```
I start seeing errors with the remote sequence
``` 
2 Jul 12:11:46 - [error] [alexa-remote-sequence:Bedroom] Error: no JSON
2 Jul 12:11:46 - [error] [alexa-remote-sequence:Kitchen] Error: no JSON
2 Jul 12:11:46 - [error] [alexa-remote-sequence:Study] Error: no JSON
```
Thanks

**Comment by 586837r** [comment]
The first thing is an expected warning. It should not cause any issues.
The `Error: no JSON` is a Cookie issue, so try reinitialising:
If you use a file path, delete the file or choose a new path.

**Comment by 586837r** [comment]
TTS to multiple devices is now easily possible in version 3 with an *Alexa Routine* node.

**Comment by BassTeQ** [comment]
Could that functionality be added? It would be very useful!
If I have music playing at level 30, I wouldn't want to make an announcement at level 80, then have the music continue at level 80 :~
Thanks

**Comment by 586837r** [comment]
Oh i meant this is **now** built in with *Speak at Volume* of the *Alexa Routine* node. 
It will play at the volume you entered and then set it back to the original volume.
Unfortunately getting the volume fails for some Echo devices if music hasn't played on them for a while...
Please update 3.0.4 because there was a bug in saving the *Alexa Routine* node configuration.

**Comment by BassTeQ** [comment]
Excellent, thanks! Will try this out in my flow.
