### ISSUE TITLE
crashes NodeRed is directory is not available in proxy options

### ISSUE THREAD

**Issue by spants** [586837r/node-red-contrib-alexa-remote2#21]
Just got this message in logs:

`[error] [alexa-remote-account:alexa] Error: EISDIR: illegal operation on a directory, read

at Server.setupListenHandle [as _listen2] (net.js:1270:14)
at listenInCluster (net.js:1318:12)
at Server.listen (net.js:1405:7)
at Function.listen (/data/node_modules/express/lib/application.js:618:24)
at Object.initAmazonProxy (/data/node_modules/alexa-cookie2/lib/proxy.js:303:22)
at Object.generateAlexaCookie (/data/node_modules/alexa-cookie2/alexa-cookie.js:337:21)
at AlexaRemote.generateCookie (/data/node_modules/node-red-contrib-alexa-remote2/tools/tools.js:11:26)
at getCookie (/data/node_modules/alexa-remote2/alexa-remote.js:98:22)
at AlexaRemote.init (/data/node_modules/alexa-remote2/alexa-remote.js:133:9)
at AlexaRemoteAccountNode._initAlexaFromObject (/data/node_modules/node-red-contrib-alexa-remote2/nodes/alexa-remote-account.js:109:15)
at fs.readFile (/data/node_modules/node-red-contrib-alexa-remote2/nodes/alexa-remote-account.js:192:38)
at FSReqWrap.readFileAfterClose [as oncomplete] (internal/fs/read_file_context.js:37:12)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! node-red-docker@1.0.0 start: `node $NODE_OPTIONS node_modules/node-red/red.js -v $FLOWS "--userDir" "/data"`
npm ERR! Exit status 1`

I had to comment out line 192 in /data/node_modules/node-red-contrib-alexa-remote2/nodes/alexa-remote-account.js to get NR up and running as I use Docker and safe mode is a problem ;-)

**Comment by 586837r** [comment]
Thanks for the report!
I'm not familiar with docker and its safe mode.
I don't understand why fs.readFile would throw?
And doesn't the stack trace show that fs.readFile was successful?
I'm confused.

**Comment by spants** [comment]
Hi - it isnt related to docker, its just that with docker it isnt possible to start NodeRed without running the flow (ie the new safe mode).
I tried to setup the Proxy without understanding what I was doing :).... It didnot have read access to the directory (I think) so it errored out and crashed NodeRed. What happens if you use a directory that doesnt exist on normal NodeRed?.
I'm using the legacy username and password method at the moment and would like to change to rpxy. Is there a how-to?

**Comment by 586837r** [comment]
If i don't have read access or it doesn't exist it calls node.warn(...) so i get a [warn] in the console and the debug tab.
There is a tutorial in the [readme](README.md) for the proxy method.
I'm don't know how i can prevent the crash you encounter. I can not reproduce it...

**Comment by spants** [comment]
ok, got a little further using a different configuration. if I setup a docker using bridge mode so that it gets its own IP (say 192.168.1.2) but my web browser on my machine (192.168.1.40), I cannot use localhost:3456. If I edit the url to change it to the server ip 192.168.1.2, if keeps changing back to localhost.

I think that this proxy (at the moment) will only work for local installations.....

**Comment by 586837r** [comment]
I have tested the proxy method before from different devices in the local network and that worked.
Where does it keep changing back to localhost? Are you running at least v2.2.0? You have to enter `192.168.1.2` in the *This IP* field.

**Comment by spants** [comment]
Thanks, silly mistake by me. Will try and document how to crash it.... I managed to get the temporary login working (This IP field!) but cant get it to store the data so it is lost on redeploy.
The File Path field - does this need filename and directory or just the path?.
I think the problem I have is with directory permissions due to the docker technology.
many thanks

**Comment by 586837r** [comment]
The path is to a file for storage, so a relative `alexa-cookie.json` or absolute `/home/pi/alexa-cookie.json`.
You can also save the cookie in your own way as described in the *Alexa Init* node info like this for example: 
```
[{"id":"323608dd.6ee4c8","type":"inject","z":"ba312d1.b9842d","name":"","topic":"","payload":"alexa","payloadType":"flow","repeat":"","crontab":"","once":false,"onceDelay":0.1,"x":120,"y":80,"wires":[["50b011bc.1d8b1"]]},{"id":"415d7558.7fbcfc","type":"change","z":"ba312d1.b9842d","name":"","rules":[{"t":"set","p":"alexa","pt":"flow","to":"payload","tot":"msg"}],"action":"","property":"","from":"","to":"","reg":false,"x":410,"y":80,"wires":[["afc17e7c.70e288"]]},{"id":"afc17e7c.70e288","type":"debug","z":"ba312d1.b9842d","name":"","active":true,"tosidebar":true,"console":false,"tostatus":false,"complete":"false","x":570,"y":80,"wires":[]},{"id":"50b011bc.1d8b1","type":"alexa-remote-init","z":"ba312d1.b9842d","name":"","account":"","x":260,"y":80,"wires":[["415d7558.7fbcfc"]]}]
```
There is also a thread about saving the cookie yourself [in this issue](https://github.com/586837r/node-red-contrib-alexa-remote2/issues/11#issuecomment-498338781).

**Comment by spants** [comment]
thanks - will switch to the other thread!
