### ISSUE TITLE
best practice (& error in example)

### ISSUE THREAD

**Issue by martinschki** [586837r/node-red-contrib-alexa-remote2#28]
Thank you for this!
Sending text to my Alexas now works perfectly

- What is the best practice in Nodered to utilize simple text to speech (TTS). I have several flows where I initiate TTS via the speak command. Is it OK to place an "Alexa Sequence" node every time or is it better to bundle and send everything to one node via links or variables?

(Oh, and the device selection doesn't work in the examples. They show an empty list.)

Thanks again for the great node.

**Comment by 586837r** [comment]
Its absolutely ok to place many Alexa Sequence nodes. It just does a function call along with status reporting. Do whatever looks neat.

Thanks for reporting the example error, i have updated the examples and fixed that error!
