### ISSUE TITLE
Upgrade from 2.3.5 to 3.0.3 failed - 404 Not Found

### ISSUE THREAD

**Issue by akowasch** [586837r/node-red-contrib-alexa-remote2#29]
Since the upgrade from version 2.3.5 to 3.0.3 I get a popup with an error message (404 Not Found) when creating an Alexa account node configuration. Also it is not possible to create an Alexa routine and change settings. The changes made will not be applied.

I have already uninstalled the module and reinstalled it, but without success.

I've been using this module for a few weeks now and everything has been running absolutely smoothly so far. Only since the new 3.0.x version it doesn't work anymore.

I would be happy to provide you with further information.

**Comment by 586837r** [comment]
The saving bugs of the Routine node should be resolved with 3.0.4, thanks for the report!

I don't know what the 404 Not Found is about. Does it happen when you deploy or just open the edit panel? Do you have a screenshot? Do you get any error in the node-red console or in the browser developer tools console?

**Comment by akowasch** [comment]
The 404 Not Found occurs every time I want to assign the created Alexa account node configuration to a Routine.

Here is a screenshot of my Alexa account node configuration:

![Bildschirmfoto 2019-07-29 um 04 27 27](https://user-images.githubusercontent.com/9094768/62101764-de8afd00-b296-11e9-9d17-bcdee7e2b679.png)

Here is an excerpt of the developer console:

![Bildschirmfoto 2019-07-29 um 12 05 03](https://user-images.githubusercontent.com/9094768/62101772-e480de00-b296-11e9-96f1-c02f8c0691a8.png)

I'm currently using version 2.3.5 again. These messages do not appear in the developer console there.

**Comment by akowasch** [comment]
3.0.6 fixed the problem! Thank you very much.
