### ISSUE TITLE
Speak routine not working after migration

### ISSUE THREAD

**Issue by mysteryan** [586837r/node-red-contrib-alexa-remote2#31]
Just updated from version 2 to 3 of alexa-remote2.  Everytime I seem to send a speak request to an echo device, it seems to send give me this error in debug.  I've inputted a simple "hi" directly into the alexa-routine node before I reprogram the flows I used from version 2 to test it, but can't seem to get that to work.  This is the error I get:
'message: "Input failed to validate."'

**Comment by 586837r** [comment]
Can you please show me what you see in the console. This is the interesting part along with the error: (you may want to mask your customerId like i did) 
```
{ raw:
   { type: 'speak',
     payload:
      { type: 'regular',
        text: { type: 'msg', value: 'payload' },
        devices: [ 'G090VC09911223ER' ] } },
  eval:
   { type: 'speak',
     payload: { type: 'regular', text: 'hi', devices: [ 'G090VC09911223ER' ] } } }
{ evaluated:
   { type: 'speak',
     payload: { type: 'regular', text: 'hi', devices: [ 'G090VC09911223ER' ] } },
  native:
   { '@type': 'com.amazon.alexa.behaviors.model.OpaquePayloadOperationNode',
     type: 'Alexa.Speak',
     operationPayload:
      { deviceType: 'A32DOYMUN6DTXA',
        deviceSerialNumber: 'G090VC09911223ER',
        locale: 'de-DE',
        customerId: 'XXX',
        textToSpeak: 'hi' } } }
Alexa-Remote: No authentication check needed (time elapsed 27366)
Alexa-Remote: Sending Request with {"host":"layla.amazon.de","path":"/api/behaviors/preview","method":"POST","timeout":10000,"headers":{}}and data={"behaviorId":"PREVIEW","sequenceJson":"{\"@type\":\"com.amazon.alexa.behaviors.model.Sequence\",\"startNode\":{\"@type\":\"com.amazon.alexa.behaviors.model.OpaquePayloadOperationNode\",\"type\":\"Alexa.Speak\",\"operationPayload\":{\"deviceType\":\"A32DOYMUN6DTXA\",\"deviceSerialNumber\":\"G090VC09911223ER\",\"locale\":\"de-DE\",\"customerId\":\"XXX\",\"textToSpeak\":\"hi\"}}}","status":"ENABLED"}
Alexa-Remote: Response: null
```

**Comment by mysteryan** [comment]
{ raw:
   { type: 'speak',
     payload:
      { type: 'regular',
        text: { type: 'str', value: 'Hello' },
        devices: [ 'G090U507842511FU' ] } },
  eval:
   { type: 'speak',
     payload: { type: 'regular', text: 'Hello', devices: [ 'G090U507842511FU' ] } } }
{ evaluated:
   { type: 'speak',
     payload: { type: 'regular', text: 'Hello', devices: [ 'G090U507842511FU' ] } },
  native:
   { '@type': 'com.amazon.alexa.behaviors.model.OpaquePayloadOperationNode',
     type: 'Alexa.Speak',
     operationPayload:
      { deviceType: 'A32DOYMUN6DTXA',
        deviceSerialNumber: 'G090U507842511FU',
        locale: 'en-US',
        customerId: 'XXX',
        textToSpeak: 'Hello' } } }
Alexa-Remote: No authentication check needed (time elapsed 123060)
Alexa-Remote: Sending Request with {"host":"pitangui.amazon.com","path":"/api/behaviors/preview","method":"POST","timeout":10000,"headers":{}}                  and data={"behaviorId":"PREVIEW","sequenceJson":"{\"@type\":\"com.amazon.alexa.behaviors.model.Sequence\",\"startNode\":{\"@type\":\"com.amazo                  n.alexa.behaviors.model.OpaquePayloadOperationNode\",\"type\":\"Alexa.Speak\",\"operationPayload\":{\"deviceType\":\"A32DOYMUN6DTXA\",\"device                  SerialNumber\":\"G090U507842511FU\",\"locale\":\"en-US\",\"customerId\":\"XXX\",\"textToSpeak\":\"Hello\"}}}","status":"ENABLED"}
Alexa-Remote: Response: {"message":"Input failed to validate."}
Alexa-Remote WS-MQTT: Initialization not done within 30s
Alexa-Remote WS-MQTT: Close: 1005:
Alexa-Remote WS-MQTT: Retry Connection in NaNs
Alexa-Remote WS-MQTT: Open: https://dp-gw-na-js.amazon.com/?x-amz-device-type=ALEGCNGL9K0HM&x-amz-device-serial=undefined-1564439052369
Alexa-Remote WS-MQTT: Initialization Msg 1 sent
Alexa-Remote WS-MQTT: Initialization Msg 2+3 sent

**Comment by 586837r** [comment]
This could happen if the customerId of the device is not the same as the one that is used there...
Can you please check if the `deviceOwnerCustomerId` of any device is not equal to the one used here?
To get the devices json use an *Alexa Echo* node with the *Get* > *Device* > *All Devices* option.

**Comment by mysteryan** [comment]
I do have devices under a different deviceOwnerCustomerId, but none of which are devices I'm trying to interact with.

That is some weird spacing on that line Sending Request.  It's a direct copy and paste from PuTTy.  Dismissed it as mangled interpretation of of structure in the text box.  

I've used the same tokens as version 2 with same devices without issue.  I've even tried initialising new credentials via proxy option, but same results.  I'll probably just downgrade back if it's too much trouble.

**Comment by 586837r** [comment]
If you get it working in version 2 then it would be great if you could post the `Alexa-Remote: sending request` and `Alexa-Remote: response` so i can see what the difference is.

In 3.0.5 it now uses the deviceOwnerCustomerId of the device, but that shouldn't solve your issue...

**Comment by mysteryan** [comment]
Actually, decided not to downgrade.  Latest few commits (3.05) seems to have resolved the issue and now seems to function as intended.
