### ISSUE TITLE
Rate exceeded, Initialisation was aborted!

### ISSUE THREAD

**Issue by BassTeQ** [586837r/node-red-contrib-alexa-remote2#32]
Trying out the updated version in my flow, seeing these errors, any ideas what may be causing them?

```
Alexa-Remote: Response: {"applianceGroups":[]}
Alexa-Remote: Response: {"message":"Rate exceeded"}

30 Jul 20:24:14 - [error] [alexa-remote-account:brad v2.2] Initialisation was aborted!

Alexa-Remote WS-MQTT: Initialization not done within 30s
Alexa-Remote WS-MQTT: Initialization not done within 30s
Alexa-Remote WS-MQTT: Close: 1005:
Alexa-Remote WS-MQTT: Retry Connection in NaNs
Alexa-Remote WS-MQTT: Close: 1005:
Alexa-Remote WS-MQTT: Retry Connection in NaNs
Alexa-Remote WS-MQTT: Open: https://dp-gw-na-js.amazon.com/?x-amz-device-type=AL
**details removed from url**
Alexa-Remote WS-MQTT: Initialization Msg 1 sent
```

**Comment by 586837r** [comment]
`Initialisation was aborted!` happens when you initialise an Account while it is already initialising.
Then the old initialisation is aborted and the new one takes over. Do you trigger initialisations in quick succession? That would also explain "Rate exceeded".

**Comment by BassTeQ** [comment]
Thanks, does the alexa sequence node do an initialise at load? If so that may be my issue, I added a initialisation node to run at startup, so that may be causing a conflict. Will remove it and see if that resolves the issue.

**Comment by 586837r** [comment]
An Account with the *Auto Init* option enabled will intialise automatically on startup or change.
You want to either use *Auto Init* or use the Initialisation node, otherwise it will init twice on startup.

**Comment by BassTeQ** [comment]
I now only have a sinlge alexa sequence node, and the account node is configured to auto initialise.
I've removed the cookie and let it reset, but still getting the error.

```
Alexa-Remote WS-MQTT: Initialization not done within 30s
Alexa-Remote WS-MQTT: Close: 1005:
Alexa-Remote WS-MQTT: Retry Connection in NaNs
Alexa-Remote WS-MQTT: Open: https://dp-gw-na-js.amazon.com/?x-amz-device-type=AL**SNIP***
Alexa-Remote WS-MQTT: Initialization Msg 1 sent
Alexa-Remote WS-MQTT: Initialization Msg 2+3 sent
Alexa-Remote WS-MQTT: Initialization not done within 30s
Alexa-Remote WS-MQTT: Close: 1005:
Alexa-Remote WS-MQTT: Retry Connection in NaNs
```
![image](https://user-images.githubusercontent.com/32693997/62352588-da3b3a00-b54b-11e9-88a8-637048502fa5.png)

**Comment by 586837r** [comment]
Looks like the event system fails to initialise. I don't know what's going wrong here...
You can disable Events in the account to prevent it from retrying forever. This only affects events, everything else works, right?

**Comment by SAABoholic** [comment]
I must be blind, but where do I disable events ?

**Comment by BassTeQ** [comment]
In the account settings area

**Comment by SAABoholic** [comment]
We're talking "Alexa Account" in the Alexa app on your phone right ? (even less choices on the web)
I have no Event settings there that I can find...

**Comment by BassTeQ** [comment]
No in the alexa settings you've configured in node red.

**Comment by SAABoholic** [comment]
LOL - Doh !   Sorry about that one... 
Never got any events triggered so I assumed there was an external setting that I needed to enable.

Back to the drawing board.... thanks  !
