### ISSUE TITLE
Not Found issue with Account (raspmatic)

### ISSUE THREAD

**Issue by ThomasPoett** [586837r/node-red-contrib-alexa-remote2#34]
![image](https://user-images.githubusercontent.com/43953071/62233652-45103800-b3c9-11e9-8e4e-5fb1ac0b87cb.png)
Mhhh, after the update some part are not working any more. I can Init the account correctly, but in the followup node, I can choose from the account, but "NOT FOUND" is stated.
I tested with manual Device Name, this still address the correct device, but i can't choose from a discovered list.

**Comment by akowasch** [comment]
This is the same issue as in #29. I also use the plugin together with redmatic.

**Comment by 586837r** [comment]
Ok the url must be relative for redmatic. Does 3.0.6 fix it?

**Comment by ThomasPoett** [comment]
3.0.6 fixed the problem
![image](https://user-images.githubusercontent.com/43953071/62354310-d2a87080-b50c-11e9-8101-416eff666e76.png)

**Comment by 586837r** [comment]
Great! (those boxes are icons in Edge/Chrome/Chromium and maybe other browsers)

**Comment by Dakyne** [comment]
Fixed … I didn't think it was related. Thanks for the help.
