### ISSUE TITLE
Alexa Event fails to initiate

### ISSUE THREAD

**Issue by SAABoholic** [586837r/node-red-contrib-alexa-remote2#36]
Not sure if I'm doing something wrong or if it's a bug/issue.

I've been trying to get the event function going ...

Alexa-Remote WS-MQTT: Open: htt ps://dp-gw-na-js.amazon.com/?x-amz-device-type=ALEGCNGL9K0HM&x-amz-device-serial=**undefined**-timeserial

Alexa-Remote WS-MQTT: Initialization Msg 1 sent
Alexa-Remote WS-MQTT: Initialization Msg 2+3 sent
Initialization not done within 30s
Alexa-Remote WS-MQTT: Close: 1005
Alexa-Remote WS-MQTT: Retry Connection in **NaN**s

I tried renaming the event node to the serial# of one of my devices, hoping that would make a difference, but no luck there....

**Comment by SAABoholic** [comment]
Any chance it might have to do with the cookie handling in alexa-wsmqtt.js since it seems to be looking for a cookie from Amazon.de ?  if (cookie) serialArr = cookie.match(/ubid-**acbde**=([^;]+);/);
where's mine is from the .com, i.e. ubid-**main**=....

**Comment by 586837r** [comment]
I see you also opened an issue in alexa-remote. That's the way to go! I hope you find a solution.

**Comment by SAABoholic** [comment]
Sorry, yes I did once I figured it was most likely the issue....   I can confirm that it was related to the cookie and changing abcde to main made it work. 

Thanks !

**Comment by 586837r** [comment]
Version 3.1.0 should fix this then!
