### ISSUE TITLE
Have to re-authorise after every deploy - bug?

### ISSUE THREAD

**Issue by cymplecy** [586837r/node-red-contrib-alexa-remote2#37]
Lovely node but everytime I redeploy the flow, I have to goto localhost:3456 and re-authorise

Is this just the way it is or have I got a bug?

**Comment by akowasch** [comment]
You may not have defined the file path in the Alexa account node configuration. Only with a valid file path the cookie is stored persistently and is read in again after a Redeploy. If a file path has been set, the permissions may not match. In this case I would check if the file was created and contains a cookie.

**Comment by 586837r** [comment]
You should see a warning in the debug log if saving or loading the file didn't work.

**Comment by cymplecy** [comment]
"you may not have defined the file path in the Alexa account node configuration. "
That was it :)
Thanks
