### ISSUE TITLE
TypeError: failed to initialise smarthome colors

### ISSUE THREAD

**Issue by itsmeduhdoi** [586837r/node-red-contrib-alexa-remote2#42]
i'm getting this error message in my debug panel when i deploy, i've tried removing and reinstalling, but it still shows up

everything seems to work though

9/12/2019, 2:58:46 PMnode: 1f2b00e3.f8c86f
msg : string[312]
"TypeError: failed to initialise smarthome colors: "Cannot read property 'parameters' of undefined"↵ at AlexaRemoteExt.initSmarthomeColorsExt (/data/node_modules/node-red-contrib-alexa-remote2/lib/alexa-remote-ext.js:307:35)↵ at <anonymous>↵ at process._tickCallback (internal/process/next_tick.js:189:7)"

**Comment by bwims** [comment]
Have you got a sonoff tasmota emulating a Philips Hue?  If so, change the emulation to be a Wemo switch.   I had the same problem and fixed it this way.  If the device doesn't support colours, you don't want to pretend to be a Hue.

**Comment by 586837r** [comment]
This is more of a warning than an error. It means you won't be able to set a color or color temperature for a smarthome device. Do you have a smarthome device that should support color controlling? If you don't, then everything's fine.

**Comment by itsmeduhdoi** [comment]
> This is more of a warning than an error. It means you won't be able to set a color or color temperature for a smarthome device. Do you have a smarthome device that should support color controlling? If you don't, then everything's fine.

i don't think i do, at least at the moment

this would be an issue from devices that are connected through my amazon alexa account right? i can go check through them.

**Comment by itsmeduhdoi** [comment]
> Have you got a sonoff tasmota emulating a Philips Hue? If so, change the emulation to be a Wemo switch. I had the same problem and fixed it this way. If the device doesn't support colours, you don't want to pretend to be a Hue.

hmm,
no i don't think i do. there could be something setup that emulating a hue though, i'll check my alexa devices.

Thanks!

**Comment by bwims** [comment]
Actually, I thought I had fixed this but it still occurs after every reboot!

TypeError: failed to initialise smarthome colors: "Cannot read property 'parameters' of undefined"    at AlexaRemoteExt.initSmarthomeColorsExt (/mnt/dietpi_userdata/node-red/node_modules/node-red-contrib-alexa-remote2/lib/alexa-remote-ext.js:307:35)    at processTicksAndRejections (internal/process/task_queues.js:86:5)

**Comment by bwims** [comment]
> This is more of a warning than an error. It means you won't be able to set a color or color temperature for a smarthome device. Do you have a smarthome device that should support color controlling? If you don't, then everything's fine.

Is there any possibility that this is interacting with the Ben Hardhill alexa skills node-red contrib ?

If not it would be really nice to be able to suppress this message.

**Comment by 586837r** [comment]
The virtual devices created with Ben Hardill work just like regular smarthome devices. These nodes work well together.

In version 3.2.3 you should now only see this warning if  something is actually going wrong.
