### ISSUE TITLE
Problem with authentication via proxy

### ISSUE THREAD

**Issue by BerndSc** [586837r/node-red-contrib-alexa-remote2#43]
Hi, 
I'm trying to use the authentication via proxy. I've set the file path to '/temp/', the folder has read/write access for all. But when I enter the credentials, I get the following error:
"EISDIR: illegal operation on a directory, open '/temp/'"

Am I doing something wrong? NodeRed runs on a Raspberry Pi Zero W.

Regards,
Bernd

**Comment by 586837r** [comment]
The File Path needs to be the path to a file and not a folder so "/temp/alexa.json" should work.

**Comment by BerndSc** [comment]
Cool thanks, it works!
