### ISSUE TITLE
routine node type can't be changed

### ISSUE THREAD

**Issue by eRudy** [586837r/node-red-contrib-alexa-remote2#45]
Hello.

I can't change the type of routine nodes, for "custom" for example. They go back to type "speak" as soon as I close the settings.

And whatever I send to these nodes they always generate the same error:
"invalid sequence node: "{"type":"speak"}" expected layout: "{"type":"","payload":{}}""

I'm on version 3.2.1, tried to reload node-red with no more luck.

Maybe I made something wrong... ?

**Comment by 586837r** [comment]
What version of Node-RED do you have?

**Comment by eRudy** [comment]
I was on 0.17.something, upgraded to 0.20.8, and this solve the issue.
Now I have another issue, but maybe it's because of me again...

I will open another issue if needed ;)

Thank you for your answer and help.
