### ISSUE TITLE
Bluetooth operations don't work

### ISSUE THREAD

**Issue by bwims** [586837r/node-red-contrib-alexa-remote2#53]
The Bluetooth option shows me that my Echo has a particular device connected, and there is an option to disconnect, along with Pair and Unpair.  However, when I invoke it, I get the following error:

ReferenceError: action is not defined

Also, having disconnected "manually" (by voice), the 3 options do not change: Pair, Unpair, Disconnect.

I would like to disconnect and reconnect to bluetooth at set times of the day, the window during which my hifi is switched on.

**Comment by 586837r** [comment]
Woops looks like i forgot to test this. Pair, Unpair and Disconnect should work now (version 3.2.8). All three options are always available in the node.

**Comment by bwims** [comment]
Wonderfully quick work!  I don't suppose you would consider adding a connect option?  I can ask Echo to connect speakers and it looks for what it is paired to and does it.

Thanks!

**Comment by 586837r** [comment]
I can't test it at the moment but i think pair also connects the bluetooth device. Does that work?

**Comment by bwims** [comment]
Yes!  Many thanks!
