### ISSUE TITLE
Improvement: Less logging

### ISSUE THREAD

**Issue by giddyhup** [586837r/node-red-contrib-alexa-remote2#57]
There is too much information being logged. My Node-RED log level is set to error and every information/setting and activity from the Alexa nodes appears in the log.

**Comment by 586837r** [comment]
You're absolutely right. You will only see the wall of text in debug now. (v3.3.0)

**Comment by giddyhup** [comment]
Thanks for the quick response. I should add that this is awesome! I now have Alexa on three echo dots announcing that the doorbell rang. : )

**Comment by 586837r** [comment]
Awesome! I appreciate it :)
