### ISSUE TITLE
auto refresh while web page open - fails....

### ISSUE THREAD

**Issue by shodge12** [586837r/node-red-contrib-alexa-remote2#58]
So the refresh seems to work great unless you have node red open when a refresh happens.

Then for some reason, even when it says thing succeed - no output goes to the Alexa devices.  The only way I can fix it is by forcing a refresh.  Then things work again...

Anyone else see this behavior?

-Stan

**Comment by 586837r** [comment]
Unfortunately the refresh does not reliably work. I don't know why and i don't think or don't know how the open web page could affect that at all :/
Also see #40
