### ISSUE TITLE
de-DE account does not work

### ISSUE THREAD

**Issue by LucReynders** [586837r/node-red-contrib-alexa-remote2#59]
I created an account with : (this is also my account for amazon.de - for BE customers)
        GER | layla.amazon.de | amazon.de | de-DE
but the echo devices were not responding with example 1 of the GitHub info.
When I switched the account to amazon.com and en-EN everything worked fine (although I authorized with my amazon.de and password).
Seems to be a restriction from the node or the amazon API (no access for DE).

**Comment by 586837r** [comment]
Those authentication settings work fine for Germany. Maybe in Belgium you just need .com?
If you log in at alexa.amazon.com does it redirect you to alexa.amazon.de? I assume for the service host you have to choose the page that you get redirected to, if it even redirects.

**Comment by LucReynders** [comment]
I remember that I needed to switch to .com for getting access to my alexa skills like local belgian radio skills.  In the .de setting I could not access these skills.  This may be the reason for the strange behaviour.
Quite confusing,  amazonshop is .DE,  language setting in .DE is nl ,  Skills is .com ...

Luc Reynders
