### ISSUE TITLE
Updating Cookie. Automatically?

### ISSUE THREAD

**Issue by dejavue1985** [586837r/node-red-contrib-alexa-remote2#61]
Hello, newbie here. I have set it up successfully and I'm happy with the nodes. A question about updating the cookie: Is it supposed to update itself automatically? If so, it does not work for me. After the set refresh time I have to log in my Amazon account using ip.of.my.raspi:3456. then it works again until the refresh time has expired. am I doing something wrong? Thank you in advance!

**Comment by 586837r** [comment]
The node needs to save the cookie in a file for automatic refresh to work. Make sure that you entered a file path (path to file, not folder) in the account configuration. If you already did that check for any warnings in the debug log when initialising the account, there could be a warning about it not being able to save the file.

**Comment by dejavue1985** [comment]
Thanks! Worked fine! Now i'm using the following path: 

/home/pi/alexaRemoteCookie/cookie.txt

before, i created the folder and the txt-file.
