### ISSUE TITLE
Duplicates/Multiple Devices listed and monitor state.

### ISSUE THREAD

**Issue by boskoe** [586837r/node-red-contrib-alexa-remote2#63]
Thank you for developing this. 

I have managed to get authenticated with Amazon and am retrieving information from my Alexa's.
I wish to use the Smarthome node to query a Ring alarm system for alarm events. I'm able so see these events with this flow:

![image](https://user-images.githubusercontent.com/10463052/67868200-faa27280-fb01-11e9-9aa3-d142af615235.png)

A given Ring sensor will return in it's payload detectionState either "DETECTED" or "NOT_DETECTED".
This is working great however I can't see how to monitor for this change in state. I can only query when I press the injection node. Is there a way to monitor?

I've also noticed that the Smarthome Node Query Appliance/Group drop down list contains many duplicates and multiples of devices. I've checked the Alexa app and these duplicates don't exist there. 

![image](https://user-images.githubusercontent.com/10463052/67868243-13ab2380-fb02-11e9-90ce-323f4e187758.png)

Thanks for any help or nudges in the right direction.

Doug

**Comment by 586837r** [comment]
Unfortunately there is no way to monitor smarthome devices.
I suppose you can receive a smarthome event in node-red if you can create a routine that triggers on a sensor event and then turns a virtual device on / off.
You can create virtual devices with https://flows.nodered.org/node/node-red-contrib-amazon-echo for example.

Thanks for bringing duplicates to my attention. They should be gone in the next patch.

**Comment by boskoe** [comment]
Thank you for your advise on my monitoring question. I will look into your suggestion. In the meantime I'm going to use the inject node on "n" second intervals and see what happens. 

Also thank you for your hard work on these nodes. It's greatly appreciated.

**Comment by boskoe** [comment]
Apparently there is a known issue where use of Alexa and the Hue skill will produce duplicate lights.
I'm almost positive this is my problem and wasn't the fault of your node.

Thanks for your help.
