### ISSUE TITLE
Schalten von Geräten incl. Rückantwort in App?

### ISSUE THREAD

**Issue by Blackei** [586837r/node-red-contrib-alexa-remote2#64]
Hi,

wie ist es möglich einen z.B. Homemtic Schalter ein und auszuschalten und egal welchen weg ich nehme (Sprache/HomemticUI/Alexa APP) überall den richtigen status angezeigt zu bekommen?

Danke, ich verzweifle hier ein wenig....

**Comment by mloeschner** [comment]
Hi, at first, let me translate that question for others:

> How is it possible to get and keep the current state of a smart home device?

I guess the only way at the moment is to pull the state in regular intervals. However, its not clear to me if the device mentioned is an actor or a stateless button.

Deutsche Antwort: Ich denke dass das im Moment nur über regelmäßige Abfragen möglich ist. Geht es um HomeMatic IP via Accesspoint/Cloud? Handelt es sich um einen Schalter (Aktor) oder über einen Taster?

**Comment by Blackei** [comment]
Hi,
super in Deutsch...
es ist wohl möglich hier eine Rückantwort in de Alexa Welt möglich ist. Es handelt sich um einen Homematic Aktor der halt nur true und false ausgibt:

Hier ist mein Flow:

`[{"id":"481d6e70.5a0d78","type":"alexa-smart-home-v3","z":"81f2330c.a79198","conf":"326a4ce9.7d2cec","device":"3312","acknowledge":true,"name":"Licht Esszimmer","topic":"","x":100,"y":200,"wires":[["440f3f08.31ef2"]]},{"id":"440f3f08.31ef2","type":"change","z":"81f2330c.a79198","name":"","rules":[{"t":"change","p":"payload","pt":"msg","from":"ON","fromt":"str","to":"true","tot":"bool"},{"t":"change","p":"payload","pt":"msg","from":"OFF","fromt":"str","to":"false","tot":"bool"}],"action":"","property":"","from":"","to":"","reg":false,"x":320,"y":200,"wires":[["420a614e.ba6488"]]},{"id":"420a614e.ba6488","type":"ccu-value","z":"81f2330c.a79198","name":"","iface":"BidCos-RF","channel":"MEQ0326899:1 Licht Esszimmer","datapoint":"STATE","mode":"","start":true,"change":true,"cache":true,"queue":true,"on":0,"onType":"undefined","ramp":0,"rampType":"undefined","working":false,"ccuConfig":"38263145.35ea0e","topic":"${CCU}/${Interface}/${channel}/${datapoint}","x":560,"y":200,"wires":[[]]},{"id":"326a4ce9.7d2cec","type":"alexa-smart-home-v3-conf","z":"","username":"Blackeye","mqttserver":"mq-red.cb-net.co.uk","webapiurl":"red.cb-net.co.uk"},{"id":"38263145.35ea0e","type":"ccu-connection","z":"","name":"localhost","host":"localhost","regaEnabled":true,"bcrfEnabled":true,"iprfEnabled":true,"virtEnabled":true,"bcwiEnabled":false,"cuxdEnabled":true,"regaPoll":true,"regaInterval":"30","rpcPingTimeout":"60","rpcInitAddress":"127.0.0.1","rpcServerHost":"127.0.0.1","rpcBinPort":"2047","rpcXmlPort":"2048","queueTimeout":"5000","queuePause":"250","contextStore":""}]`


Und der Rückkanal benötigt wohl folgendes:
`msg {
    acknowledge: true,
    payload {
        state { 
            "brightness": 0-100,
            "colorbrightness": 0-1,
            "colorHue": 0-360,
            "colorSaturation": 0-1,
            "colorTemperature": 0-10000, 
            "input": string,
            "lock": "LOCKED" || "UNLOCKED",
            "percentage": number,
            "percentageDelta": number,
            "playback": playback,
            "power": "ON" || "OFF",
            "temperature": number,
            "thermostatMode": "HEAT" || "COOL",
            "thermostatSetPoint" : number,
            "targetSetpointDelta": number,
            "volume": number,
            "volumeDelta": number
        }
    }
}`

Ich kann das einfach nicht.....

**Comment by 586837r** [comment]
Ich habe selber kein Homematic und weiß auch nicht was der beste Weg ist das mit Alexa zu verbinden.

Aber so kannst du den an/aus Status von alexa-smarthome-v3 Geräten updaten:
```
[{"id":"5942156c.47b11c","type":"function","z":"14411b83.58e534","name":"","func":"return {\n  acknowledge: true,\n  payload: {\n    state: { \n      power: msg.payload ? \"ON\" : \"OFF\"\n    }\n  }\n}","outputs":1,"noerr":0,"x":250,"y":200,"wires":[["fb63ad9d.22bca"]]},{"id":"43b6797.cff8188","type":"inject","z":"14411b83.58e534","name":"","topic":"","payload":"true","payloadType":"bool","repeat":"","crontab":"","once":false,"onceDelay":0.1,"x":110,"y":180,"wires":[["5942156c.47b11c"]]},{"id":"31d7c0da.2b617","type":"inject","z":"14411b83.58e534","name":"","topic":"","payload":"false","payloadType":"bool","repeat":"","crontab":"","once":false,"onceDelay":0.1,"x":110,"y":220,"wires":[["5942156c.47b11c"]]},{"id":"fb63ad9d.22bca","type":"alexa-smart-home-v3-state","z":"14411b83.58e534","conf":"","device":"3334","name":"","x":440,"y":200,"wires":[]}]
```

Du solltest vielleicht wo anders fragen, meine nodes haben nichts mit dem Einbinden von virtuellen Geräten oder Homematic zu tun.

**Comment by Blackei** [comment]
Hi,
super!!!! es funktioniert perfekt....wenn du mir jetzt noch zeigst wie es bei einem Dimmer aussieht, bin ich vollkommen glücklich..... 
Schade das Rollladen noch nicht so richtig funktionieren, aber vielleicht kommt da jetzt durch IKEA ja etwas....

Und vielen Dank für die Hilfe.....

**Comment by 586837r** [comment]
Zum Dimmer status updaten einfach eine message mit einem `brightness` feld mit einem numerischen Wert anstatt `power`.

**Comment by Blackei** [comment]
Hi,

ich musste den brightness mal 100 nehmen und Power dazu damit an/aus auch funktioniert.

Vielen, vielen Dank....
