### ISSUE TITLE
Bug in Remote Routine that uses a skill

### ISSUE THREAD

**Issue by moryoav** [586837r/node-red-contrib-alexa-remote2#65]
Amazon recently added an option to call skills from within routines. I have a routine that does a bunch of smart home stuff and then activates a skill. When calling this routine ("Alexa, routine name"), this works fine. When calling this routine from node red using the Remote Routine node, all the routine actions are performed except for the skill launch which doesn't start.

**Comment by 586837r** [comment]
Hmm i just created a routine in the app that turns some lights on and off and then opens the "dog bark" skill. I was able to use "Execute Routine" in node red and it did bark. 
Does that simple example work for you? 
Do you have an example where it does not work?

Make sure that you select a valid Echo device in the node.

**Comment by moryoav** [comment]
Here's what I discovered: if you create a routine in the app which does not contain a skill, then set everything up in node-red, deploy, then go and add the skill, it doesn't work. If you Redeploy, it then works. So it seems that the deploy stage reloads all the instructions from the routine, it's not something that can be updated in the routine and it'll just work. Good to know...

**Comment by 586837r** [comment]
Oh yeah that's somewhat unintuitive. When the account initialises it loads all the routine instructions. It's not like an id that gets sent for execution but the previously loaded routine instructions.
