### ISSUE TITLE
Warning after recent upgrade

### ISSUE THREAD

**Issue by moryoav** [586837r/node-red-contrib-alexa-remote2#68]
I get the following warning in the debug console:

building bluetooth for ui failed: "Hostname/IP does not match certificate's altnames: Host: skills-store.amazon.de. is not in the cert's altnames: DNS:skills-store.amazon.com.mx, DNS:skills-store.amazon.ca, DNS:skills-store.amazon.com, DNS:skills-store.amazon.com.br""

I removed the saved cookie and re-authorized, it didn't help.

**Comment by 586837r** [comment]
Thanks for the report! Should be fixed in 3.4.1
