### ISSUE TITLE
executeAutomationRoutine

### ISSUE THREAD

**Issue by Prog72** [586837r/node-red-contrib-alexa-remote2#7]
These nodes looks very promising indeed. Great work!

However, I can't get executeAutomationRoutine to do anything. I presume it should launch routines but nothing happens. Is the Automation Id the name of the routine?

**Comment by Prog72** [comment]
After some more playing around I've used the get automationRoutines node to find the Automation IDs of the routine in question. However, it's still not working although the node reports success. I've tried several routines to no avail.

**Comment by 586837r** [comment]
Thank you and thanks for reporting the issue!
executeAutomationRoutine works now with either an utterance or the automationId in version 1.0.6

**Comment by Prog72** [comment]
Working perfectly now. Many thanks.
