### ISSUE TITLE
Change volume of echo-speaker relatively?

### ISSUE THREAD

**Issue by dejavue1985** [586837r/node-red-contrib-alexa-remote2#71]
Hello, Is there a way to change the volume of an Echo speaker relatively? Just like with the command "Alexa, louder" starting from the current volume?

I have a zigbee switch which i would like to use to in-/decrease the volume of a specific echo speaker.

all i found is the option to set the volume absolutely to an specific value.

regards

**Comment by 586837r** [comment]
There was no easy way to do this. In version 3.6.0 you can choose the *Add* option. So with a value of 10 it would be like saying "Alexa, louder" or -10 like "Alexa, quieter".

Keep in mind that changing the Volume relatively is only reliable if the echo is or was recently playing music.

Thanks for the suggestion!
