### ISSUE TITLE
Push Notification topic frei wählbar

### ISSUE THREAD

**Issue by Matten-Matten** [586837r/node-red-contrib-alexa-remote2#76]
Hallo, ist es möglich bei Push Notification ein msg.topic oder so einzufügen? momentan steht dort statisch **Node-RED** 
![Screenshot_20191201_121516](https://user-images.githubusercontent.com/32074970/69913205-051f9700-1435-11ea-9733-01eaf360e6b1.jpg)

vielleicht so?:
`{ type: 'pushNotification', payload: { topic: 'Node-RED oder XYZ', payload: text: 'Hello from Node-RED!' }}`

**Comment by 586837r** [comment]
Ja das ist kein problem. Ich denke eine neue property "title" im payload wäre passend.

**Comment by Matten-Matten** [comment]
Ja oder so! Perfekt

**Comment by 586837r** [comment]
Ist in 3.7.0

**Comment by Matten-Matten** [comment]
super Danke!
