### ISSUE TITLE
[Request] Listen to Alexa Events from sensors?

### ISSUE THREAD

**Issue by moryoav** [586837r/node-red-contrib-alexa-remote2#77]
I have an Alexa supported door sensor (Tuya, wifi sensor). In the Alexa app it's recognized as a sensor and I can add a routine where IF the door is closed\open THEN alexa does something. Under "When This Happens" in the Alexa app routines, there's a category for Smart Home. Obviously this event is fired from the Tuya servers to the Alexa servers, that part works fine. 
Is it possible to include a listener for this event in the Alexa Event node? I would love to see a Smart Home category within the Alexa Event to support those sensors. 
Thanks!

**Comment by 586837r** [comment]
No unfortunately amazon doesn't send any event for something like that. I don't think my nodes can help here.

A good way to listen to an event like this in node-red is by creating a virtual smarthome device that you turn on/off in a routine when the sensor detects something.
You can create virtual devices with node-red-contrib-alexa-smart-home, node-red-contrib-amazon-echo or others.

**Comment by Prog72** [comment]
I heartily recommend node-red-contrib-amazon-echo for this. It emulates Philips Hue so shows as a light to Alexa but can obviously be used for anything in Node-RED.
