### ISSUE TITLE
Simon Says

### ISSUE THREAD

**Issue by kartikayec** [586837r/node-red-contrib-alexa-remote2#78]
Hello.

This is a remarkable piece of work.

Just a note.

In India, when text is entered via dashboard using the example flow, the echo dot instead of uttering the text triggers the game “Simon Says”.

Regards.

**Comment by nitesh619** [comment]
What host name to use for india

**Comment by kartikayec** [comment]
alexa.amazon.in

> What host name to use for india

**Comment by kartikayec** [comment]
Not really an issue. Just an amusing happenstance.
