### ISSUE TITLE
delListItem?

### ISSUE THREAD

**Issue by Matten-Matten** [586837r/node-red-contrib-alexa-remote2#80]
Hallo ist es auch möglich Einträge aus den Listen zu entfernen?

**Comment by 586837r** [comment]
Das kommt demnächst. Ist schon in der dependency committed, aber noch kein version update. Werde ich einbauen sobald es ein Update gibt.

**Comment by 586837r** [comment]
Ist in 3.8

**Comment by Matten-Matten** [comment]
funktioniert vielen Dank!
