### ISSUE TITLE
error when using msg.payload in text box

### ISSUE THREAD

**Issue by smcgann99** [586837r/node-red-contrib-alexa-remote2#81]
"invalid sequence node: "{"type":"speak","payload":{"type":"announcement","devices":["G0911B05925316LT"]}}" expected layout: "{"type":"","text":""}""

**Comment by smcgann99** [comment]
sorry my bad - forget this

**Comment by vogler** [comment]
I have the same problem, String works, but `msg.` or `flow.` complain with the above. How did you fix it?

**Comment by vogler** [comment]
Ok, it checks the type and I was using a number..., had to add `.toString()`.

**Comment by mtressl** [comment]
hey @smcgann99 and @vogler 
can you share your node examples and how you solved the issues. I am in the same place right now, but not fully get how you succeeded.

thanks in advance!

**Comment by vogler** [comment]
@mtressl Sorry, I don't remember what this was about. Which text box? I guess it only accepts strings 😄

**Comment by smcgann99** [comment]
So it depends what you are trying to do, but as an example 
msg.payload = { type: 'textCommand', payload: { text: msg.text, devices: [device] } }
