### ISSUE TITLE
File path when using Node Red in Docker container

### ISSUE THREAD

**Issue by 877dev** [586837r/node-red-contrib-alexa-remote2#87]
Took me a little while to figure the file path out, as I am using node red in a docker container.
For me, the correct file path is "/data".
e.g. ```/data/alexacookie/cookie.txt```

Basically it's the name of the internal data folder, which if you check your setup will be mapped to somewhere on your raspberry pi. (e.g /home/pi/docker/nodered/data).

Hope this helps some future searcher :)

**Comment by dougle03** [comment]
Thanks dude, worked for me.
I had to create an empty file called 'cookie.txt', then I placed in this in the /data folder and re-ran the proxy auth process.
Once I'd run the proxy process the txt file was filled in with the cookie information.
All good stuff. Thanks
