### ISSUE TITLE
"SyntaxError: Unexpected token function (line:1)"

### ISSUE THREAD

**Issue by Poquaruse** [586837r/node-red-contrib-alexa-remote2#9]
Hi,

after installing the latest version using Node-RED 0.19.5 the nodes do not work. The palette only shows the following and the nodes cannot be used...

node-red-contrib-alexa-remote2
1.0.6

    SyntaxError: Unexpected token function (line:1)
    SyntaxError: Unexpected token function (line:1)
    SyntaxError: Unexpected token function (line:1)
    SyntaxError: Unexpected token function (line:1)
    SyntaxError: Unexpected token function (line:1)
    SyntaxError: Unexpected token function (line:1)
    SyntaxError: Unexpected token function (line:1)
    SyntaxError: Unexpected token function (line:1)

Best regards

**Comment by 586837r** [comment]
It works for me on 3 devices running node-red 0.19.5 and node version 10/8. Another user also reports reports success (#7). I can only advise to reinstall.

**Comment by Poquaruse** [comment]
Thanks for responding so fast!

v8 did the trick! I have been using the "latest" tag of the docker image -- using "v8" instead of latest makes it work. 

Thanks!
