### ISSUE TITLE
Play by ID crashes Node Red but only since 29 Jan 2020!

### ISSUE THREAD

**Issue by bwims** [586837r/node-red-contrib-alexa-remote2#91]
Have any changes occurred recently in the Alexa API that could account for the following behaviour?

I was using "Play by ID" quite successfully to get around the limitations of Alexa's station id recognition system (e.g Streaming Soundtracks is too ambiguous for it to deal with).

Since approximately 29/1/20,  Any attempt to play by station ID results in a successful call which does indeed start the desired station playing, BUT THEN the Node Red service crashes with the following error:

Jan 30 12:17:17 DietPi-Tools node-red[4861]: 30 Jan 12:17:17 - [red] Uncaught Exception:
Jan 30 12:17:17 DietPi-Tools node-red[4861]: 30 Jan 12:17:17 - TypeError: Cannot read property 'length' of undefined
Jan 30 12:17:17 DietPi-Tools node-red[4861]:     at httpsGet (/mnt/dietpi_userdata/node-red/node_modules/alexa-remote2/alexa-remote.js:1122:55)
Jan 30 12:17:17 DietPi-Tools node-red[4861]:     at IncomingMessage.res.on (/mnt/dietpi_userdata/node-red/node_modules/alexa-remote2/alexa-remote.js:752:58)
Jan 30 12:17:17 DietPi-Tools node-red[4861]:     at IncomingMessage.emit (events.js:198:15)
Jan 30 12:17:17 DietPi-Tools node-red[4861]:     at endReadableNT (_stream_readable.js:1139:12)
Jan 30 12:17:17 DietPi-Tools node-red[4861]:     at processTicksAndRejections (internal/process/task_queues.js:81:17)
Jan 30 12:17:18 DietPi-Tools systemd[1]: node-red.service: Main process exited, code=exited, status=1/FAILURE
Jan 30 12:17:18 DietPi-Tools systemd[1]: node-red.service: Unit entered failed state.
Jan 30 12:17:18 DietPi-Tools systemd[1]: node-red.service: Failed with result 'exit-code'.

Please let me know if you need any other information.

**Comment by Matten-Matten** [comment]
ich habe ähnliches zu vermerken:

```
Jan 30 16:44:45 ccu3-webui daemon.err node-red: 30 Jan 16:44:45 - [red] Uncaught Exception:
Jan 30 16:44:45 ccu3-webui daemon.err node-red: 30 Jan 16:44:45 - TypeError: Cannot read property 'length' of undefined
Jan 30 16:44:45 ccu3-webui daemon.err node-red:     at httpsGet (/usr/local/addons/redmatic/var/node_modules/node-red-contrib-alexa-remote2/node_modules/alexa-remote2/alexa-remote.js:1122:55)
Jan 30 16:44:45 ccu3-webui daemon.err node-red:     at IncomingMessage.res.on (/usr/local/addons/redmatic/var/node_modules/node-red-contrib-alexa-remote2/node_modules/alexa-remote2/alexa-remote.js:752:58)
Jan 30 16:44:45 ccu3-webui daemon.err node-red:     at IncomingMessage.emit (events.js:203:15)
Jan 30 16:44:45 ccu3-webui daemon.err node-red:     at endReadableNT (_stream_readable.js:1143:12)
Jan 30 16:44:45 ccu3-webui daemon.err node-red:     at process._tickCallback (internal/process/next_tick.js:63:19)
Jan 30 16:44:45 ccu3-webui daemon.err node-red: Node-RED exited with non-zero exit status 1
Jan 30 16:44:45 ccu3-webui daemon.warn redmatic: Restarting Node-RED (1/3)
```

**Comment by 586837r** [comment]
As a workaround you can disable events in the account node for now.

**Comment by Matten-Matten** [comment]
ok danke! , jedoch schwierig da ich auf vieles gesprochene reagiere.... Denke da kommt von dir ein update für das Problem zu gegebener Zeit?

**Comment by 586837r** [comment]
Should be fixed in 3.8!

**Comment by Matten-Matten** [comment]
Super vielen Dank für dein schnellen Einsatz!

**Comment by bwims** [comment]
Many thanks!
