### ISSUE TITLE
Play tones before making annoucement?

### ISSUE THREAD

**Issue by jcwren** [586837r/node-red-contrib-alexa-remote2#93]
Is there a way to have the node play a tone, chime, or something before speaking? I find it rather disconcerting to have Alexa suddenly start talking without a bit of warning.

It may be possible to do this with dynamic content, but I'd really like to be able to do it as an option for any node that wants to speak.

**Comment by Prog72** [comment]
Announcements are always preceded by a chime on my Echos.

**Comment by jcwren** [comment]
Nope. I used the 'Alexa Speak Dashboard' demo flow in the examples.md file, go to xxx:1880/ui, select the Echo, type 'Test', click Speak, and Alexa just says "Test", with no preceding chimes, etc.

**Comment by Prog72** [comment]
Try announce rather than speak in the node.

**Comment by jcwren** [comment]
OK, that's better. Anyway to change to chime?

**Comment by Prog72** [comment]
Not that I'm aware of unfortunately.

**Comment by jcwren** [comment]
Bummer. Thanks for the help!

**Comment by Prog72** [comment]
No problem. Glad you got it sorted.
