### ISSUE TITLE
Update Smarthome node to allow user to prevent entire msg object from being overwritten

### ISSUE THREAD

**Issue by zkniebel** [586837r/node-red-contrib-alexa-remote2#96]
_First off, I'm a huge fan of this repo, and I very much appreciate the effort you put into maintaining it._

**Summary**
As an enhancement, I'd like to request that a new option be added to the Smarthome node to allow the user to specify the property of the `msg` object in which the output of the node should be stored. 

**Current behavior**
On the Smarthome node, the user does not have the ability to specify a property of the `msg` in which to store the output of the node, and the node is written to completely replace the `msg` object leaving no way for the user to pass data from an upstream node to a downstream node after the Smarthome node. 

**Desired behavior**
The user specifies the name of a property of the `msg` object in which to store the output message of the Smarthome node.

**Why this is a problem**
Often times, downstream nodes are dependent on details passed in by an upstream node. By completely overwriting the `msg` object, the user is left with no viable way to pass data from an upstream node through the Smarthome node and to a subsequent downstream node. 

**Example use-case**
The Smarthome node can be used to query the device state of a smarthome device connected to Alexa. If a user were to want to run some conditional logic based on property values added to the `msg` object upstream of the Smarthome node as well as the resulting output of the Smarthome node then a user would be unable to do so without using an additional node/set of nodes downstream of the Smarthome node to set the values that were calculated upstream again (if this is even feasible, based on where the message originated). 

Thanks so much.

**Comment by 586837r** [comment]
Good point. Most of these nodes just discard the input msg which is definitely bad behaviour.
Currently the node also writes to *id*, *topic* and *type* along with *payload* which could be quite annoying if you want to store stuff there yourself.
Providing options for all of those properties sounds excessive. I suppose keeping everything to payload, as most nodes do would be ok?
I'm not sure how the output format should look like. There is also the difference between *All Properties* and a specific choice...
What do you think?

**Comment by zkniebel** [comment]
Yeah, that would work great - instead of setting those as properties of `msg` setting them as properties of `msg.payload`.

What I meant by a user-specified property was exactly that, only with the change that the user could specify that it would be `msg.x` instead of `msg.payload`. Even so, that too might be more effort than it’s worth and putting everything into `msg.payload` certainly resolves the issue.

**Comment by zkniebel** [comment]
That's a really good point too. I agree, it would definitely be cumbersome to create a different option for specifying each property.

What if we preserve the existing functionality but apply it to `msg.payload` instead of `msg`? We could set the `id`, `topic` and `type` properties of `msg.payload` and perhaps set `msg.payload.result` to the "response" (what's currently stored in `msg.payload`). This should be relatively low effort to apply across the board, regardless of whether it's a Query for all or a specific property, or even an action. It also has the benefit of requiring changes to a minimal amount of the existing implementation.

What do you think?

**Comment by zkniebel** [comment]
The issue of breaking changes is a big concern for me, and the proposed change is rampant with them.

As an alternative, we could further simplify the implementation by updating it to use the existing `msg` object (instead of creating a new one) and overwrite the existing `id`, `topic` and `type` properties. This would also mean that we would need to remove the call to delete the rest of the properties, as well. 

Pros:
- Change even less of the existing implementation
- No breaking changes
- Users can pass data through by storing it in one of the properties that aren't used by the node
- Documentation can be updated to inform users of the properties that will be overwritten and that any pass-through data should be stored in other properties

Cons:
- Could still overwrite user-data, though docs should handle
- Requires some effort (I don't know, I'm struggling on the cons haha)

**Comment by 586837r** [comment]
Thanks, proposal 2 is now implemented in 3.9
